import { ShrimpHabitatBehavior, habitatBehaviorFor, personalityFor } from './personality';

export type HabitatZone='open-water'|'substrate'|'plants'|'equipment'|'school';
export type HabitatPose={behavior:ShrimpHabitatBehavior;zone:HabitatZone;xBias:number;yBias:number;dwellMs:number;bubbleChance:number;speedScale:number};
export type SocialMomentKind='school-run'|'feeding-rush'|'bubble-rally'|'market-panic'|'personality-parade';
export type SocialMoment={kind:SocialMomentKind;durationMs:number;spread:number;verticalBias:number;bubbleIntensity:number;reactionCadenceMs:number};
function hashSeed(seed:string){let hash=2166136261;for(let i=0;i<seed.length;i+=1){hash^=seed.charCodeAt(i);hash=Math.imul(hash,16777619);}return hash>>>0;}
function unit(seed:string){return(hashSeed(seed)%1000)/999;} function signed(seed:string){return unit(seed)*2-1;} function tankPopulation(seed:string){const match=/^tank-(\d+)$/.exec(seed);return match?Math.max(0,Math.min(12,Number(match[1]))):undefined;}
export function habitatPoseFor(seed:string,cycle=0):HabitatPose{const safeCycle=Math.max(0,Math.floor(cycle)),behavior=habitatBehaviorFor(seed,safeCycle),profile=personalityFor(seed),jitterX=signed(`${seed}-${safeCycle}-x`),jitterY=signed(`${seed}-${safeCycle}-y`),dwellJitter=.82+unit(`${seed}-${safeCycle}-dwell`)*.38;const base:Record<ShrimpHabitatBehavior,Omit<HabitatPose,'behavior'>>={patrol:{zone:'open-water',xBias:jitterX*.95,yBias:jitterY*.48,dwellMs:4200,bubbleChance:.12,speedScale:1.18},graze:{zone:'substrate',xBias:jitterX*.82,yBias:.72+jitterY*.12,dwellMs:6200,bubbleChance:.22,speedScale:.62},hide:{zone:'plants',xBias:jitterX<0?-.82:.82,yBias:.28+jitterY*.18,dwellMs:7600,bubbleChance:.08,speedScale:.42},rest:{zone:'substrate',xBias:jitterX*.48,yBias:.82+jitterY*.08,dwellMs:9200,bubbleChance:.05,speedScale:.24},inspect:{zone:'equipment',xBias:.72+jitterX*.14,yBias:-.12+jitterY*.22,dwellMs:5600,bubbleChance:.18,speedScale:.7},school:{zone:'school',xBias:jitterX*.28,yBias:jitterY*.2,dwellMs:5000,bubbleChance:.32,speedScale:.9}};const pose=base[behavior],fast=profile.name==='Hyper'||profile.name==='Intern'||profile.name==='Paper Hands',patient=profile.name==='Lazy'||profile.name==='Diamond Hands',social=profile.name==='Social'||profile.name==='Rainmaker'||profile.name==='Market Maker',forager=profile.name==='Greedy'||profile.name==='Curious',temperament=fast?.78:patient?1.28:1,speedTemperament=fast?1.38:patient?.62:social?1.16:forager?1.08:1,bubbleTemperament=social?1.72:forager?1.38:fast?1.2:patient?.72:1;return{...pose,behavior,dwellMs:Math.round(pose.dwellMs*dwellJitter*temperament),speedScale:Math.max(.18,Math.min(1.7,pose.speedScale*speedTemperament)),bubbleChance:Math.max(.03,Math.min(.72,pose.bubbleChance*bubbleTemperament))};}
/** Keep the aquarium visibly alive without turning it into a constant effects reel. Filled desks burst more often, with a deterministic quiet beat every sixth cycle so spectacles still have contrast. */
export function socialMomentDelay(seed:string,cycle=0){const population=tankPopulation(seed);if(population!==undefined){const safeCycle=Math.max(0,Math.floor(cycle)),fullness=Math.max(0,Math.min(1,(population-3)/9)),quietBeat=safeCycle>0&&safeCycle%6===5,base=population>=3?11200-fullness*3400:17000,span=population>=3?3600-fullness*1200:5600,quietBonus=quietBeat?4200:0;return Math.round(base+unit(`${seed}-${safeCycle}-social`)*span+quietBonus);}const profile=personalityFor(seed),social=profile.name==='Social'||profile.name==='Rainmaker'||profile.name==='Market Maker';return Math.round((social?9200:14200)+unit(`${seed}-${Math.max(0,cycle)}-social`)*(social?6200:9800));}
/**
 * Social beats use rotating story reels instead of a single repeating loop. Mature tanks
 * therefore feel like a trading floor with different sessions: orderly formation, food
 * rushes, bubble celebrations, panic, and personality/accessory showcases. The reel is
 * deterministic for a given tank/cycle so tests and replays remain stable.
 */
export function socialMomentFor(seed:string,cycle=0):SocialMoment{const safeCycle=Math.max(0,Math.floor(cycle)),population=tankPopulation(seed)??0;const reels:SocialMomentKind[][]=population>=12?[
['bubble-rally','market-panic','personality-parade','feeding-rush','school-run','personality-parade','bubble-rally','school-run'],
['feeding-rush','personality-parade','market-panic','bubble-rally','personality-parade','school-run','feeding-rush','bubble-rally'],
['personality-parade','school-run','bubble-rally','feeding-rush','market-panic','personality-parade','feeding-rush','school-run']
]:population>=10?[
['personality-parade','school-run','feeding-rush','bubble-rally','market-panic','personality-parade','school-run','bubble-rally'],
['feeding-rush','bubble-rally','personality-parade','market-panic','school-run','personality-parade','feeding-rush','bubble-rally']
]:population>=7?[
['personality-parade','school-run','feeding-rush','bubble-rally','market-panic','personality-parade','school-run'],
['school-run','bubble-rally','feeding-rush','personality-parade','market-panic','feeding-rush','personality-parade']
]:population>=5?[
['personality-parade','school-run','feeding-rush','bubble-rally','market-panic','school-run'],
['feeding-rush','personality-parade','bubble-rally','school-run','market-panic','personality-parade']
]:population>=3?[
['personality-parade','school-run','feeding-rush','bubble-rally','market-panic'],
['school-run','feeding-rush','personality-parade','market-panic','bubble-rally']
]:[['school-run','feeding-rush','bubble-rally','market-panic']];const reelLength=reels[0].length,reelIndex=Math.floor(safeCycle/reelLength)%reels.length,reel=reels[reelIndex],kind=reel[safeCycle%reel.length],jitter=.88+unit(`${seed}-${safeCycle}-moment-jitter`)*.24;const base:Record<SocialMomentKind,Omit<SocialMoment,'kind'>>={'school-run':{durationMs:4600,spread:.34,verticalBias:-.10,bubbleIntensity:.38,reactionCadenceMs:180},'feeding-rush':{durationMs:3600,spread:.58,verticalBias:-.64,bubbleIntensity:.82,reactionCadenceMs:98},'bubble-rally':{durationMs:5000,spread:.76,verticalBias:0,bubbleIntensity:1.34,reactionCadenceMs:164},'market-panic':{durationMs:2900,spread:1,verticalBias:.14,bubbleIntensity:1.02,reactionCadenceMs:64},'personality-parade':{durationMs:6200,spread:.8,verticalBias:-.10,bubbleIntensity:1.08,reactionCadenceMs:98}};const moment=base[kind],maturity=Math.max(0,Math.min(1,(population-3)/9)),earlyDesk=population>=3&&population<5?1.16:1,fullTank=population>=12?1.42:population>=10?1.18:1,kindPunch=kind==='market-panic'?1.18:kind==='bubble-rally'?1.12:kind==='feeding-rush'?1.06:kind==='personality-parade'?1.22:.9,headline=population>=7&&safeCycle>0&&safeCycle%7===0,sessionEnergy=.9+unit(`${seed}-${safeCycle}-session-energy`)*.22,headlinePunch=headline?1.38:1,spectacle=(1+maturity*.68)*fullTank*kindPunch*earlyDesk*sessionEnergy*headlinePunch;return{...moment,kind,durationMs:Math.round(moment.durationMs*jitter*((kind==='school-run'||kind==='personality-parade')?1+maturity*.12:1+maturity*.05)*(headline?1.18:1)),spread:Math.min(1,moment.spread*(1+maturity*.38)*(kind==='school-run'?1:fullTank)*(headline?1.12:1)),bubbleIntensity:Math.min(2.5,moment.bubbleIntensity*spectacle),reactionCadenceMs:Math.max(32,Math.round(moment.reactionCadenceMs*(1-maturity*.44)/(kind==='school-run'?1:fullTank)/(headline?1.28:1)))};}
/** Formation geometry is part of the spectacle: each event has a recognisable silhouette instead of merely firing reactions in place. */
export function socialFormationOffset(index:number,total:number,moment:SocialMoment){const safeTotal=Math.max(1,Math.floor(total)),safeIndex=Math.max(0,Math.min(safeTotal-1,Math.floor(index))),centered=safeTotal===1?0:(safeIndex/(safeTotal-1))*2-1,alternating=safeIndex%2===0?1:-1;if(moment.kind==='market-panic'){const side=centered<0?-1:1,withinSide=(safeIndex%(Math.ceil(safeTotal/2)))/Math.max(1,Math.ceil(safeTotal/2)-1);return{x:side*(.28+withinSide*.72)*moment.spread,y:moment.verticalBias+alternating*.46-centered*.24};}if(moment.kind==='feeding-rush'){const funnel=Math.pow(Math.abs(centered),1.35)*.38;return{x:centered*moment.spread*.46,y:moment.verticalBias+funnel+alternating*.028};}if(moment.kind==='bubble-rally'){const wave=Math.sin((centered+.08)*Math.PI*1.55)*.34,edgeLift=-Math.pow(Math.abs(centered),1.7)*.10;return{x:centered*moment.spread,y:moment.verticalBias+wave+edgeLift+alternating*.045};}if(moment.kind==='personality-parade'){const row=alternating*.23,arc=-Math.cos(centered*Math.PI)*.17;return{x:centered*moment.spread*.94,y:moment.verticalBias+row+arc};}const chevron=Math.pow(Math.abs(centered),1.15)*.24,leader=safeIndex===Math.floor((safeTotal-1)/2)?-.10:0,ripple=safeTotal>=5?alternating*.035:0;return{x:centered*moment.spread,y:moment.verticalBias+chevron+leader+ripple};}
