import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, useWindowDimensions, View } from 'react-native';
import { CapitalHeader } from '../components/CapitalHeader';
import { DailyRewardCard } from '../components/DailyRewardCard';
import { MissionPanel } from '../components/MissionPanel';
import { OfflineReport } from '../components/OfflineReport';
import { PixelShrimp } from '../components/PixelShrimp';
import { PixelText } from '../components/PixelText';
import { StockBrowser } from '../components/StockBrowser';
import { Tank } from '../components/Tank';
import { TankConditionPanel } from '../components/TankConditionPanel';
import { species } from '../game/catalog';
import { useGame } from '../game/GameProvider';
import { conditionMultiplier, currentBiome, lineageLabel, lineageMultiplier, saleXpFor, secondsUntilNextHatch, tankHealth, totalShrimp, valueMultiplier, xpForNextLevel } from '../game/engine';
import { colors } from '../theme/colors';

type AmbientEvent='inspection'|'power'|'visitor'|'treasure'|null;
const biomeNames={ 'starter-office':'BEDROOM BROKERAGE','trading-floor':'SHELL STREET FLOOR','executive-reef':'EXECUTIVE REEF','offshore-fund':'OFFSHORE FUND' } as const;

export function FarmScreen(){
  const {width}=useWindowDimensions();const mobile=width<700;const narrow=width<430;
  const {state,hatchNow,sellOne,selectSpecies,offlineHatches,dismissOfflineReport,claimMission,claimDailyReward,feed,service,placedDecor}=useGame();
  const [feedingFrenzy,setFeedingFrenzy]=useState(false),[ambientEvent,setAmbientEvent]=useState<AmbientEvent>(null),[inspectId,setInspectId]=useState<string|null>(null),[jumpingShrimp,setJumpingShrimp]=useState(false);
  const current=species.find(item=>item.id===state.selectedSpecies)??species[0],inspected=species.find(item=>item.id===inspectId)??null;
  const tankFull=totalShrimp(state)>=state.tankCapacity,nextHatch=secondsUntilNextHatch(state),health=tankHealth(state),conditionRate=Math.round(conditionMultiplier(state)*100),salePrice=Math.round(current.basePrice*valueMultiplier(state,current.id));
  const tintOpacity=Math.max(0,(78-state.conditions.waterQuality)/145),tintColor=state.conditions.waterQuality<45?'#6D6830':'#557C55';
  const hour=new Date().getHours(),isNight=hour>=19||hour<7,biome=currentBiome(state),selectedLineage=state.lineage[current.id]??0;
  useEffect(()=>{let timer:ReturnType<typeof setTimeout>;const schedule=()=>{timer=setTimeout(()=>{const events:AmbientEvent[]=['inspection','power','visitor','treasure'];setAmbientEvent(events[Math.floor(Math.random()*events.length)]);setTimeout(()=>setAmbientEvent(null),4200);schedule();},22000+Math.random()*32000);};schedule();return()=>clearTimeout(timer);},[]);
  const handleFeed=()=>{if(state.cash<2||state.conditions.feeding>=98)return;feed();setFeedingFrenzy(true);setTimeout(()=>setFeedingFrenzy(false),1800);};
  const inspectedAccessories=inspected?state.shrimpAccessories[inspected.id]??{chain:0,crown:0,visor:0,suit:0}:null;
  const inspectAccessory=inspectedAccessories?.suit?'suit':inspectedAccessories?.visor?'visor':inspectedAccessories?.crown?'crown':inspectedAccessories?.chain?'chain':undefined;
  const inspectSeed=inspected?inspected.id.length*17+(state.shrimp[inspected.id]??0)*3+state.level:0;
  const xpPct=Math.min(100,state.xp/xpForNextLevel(state.level)*100);
  const showTankEvent=!jumpingShrimp;

  return <LinearGradient colors={['#06131A','#08222B','#07161D']} style={styles.page}>
    <OfflineReport amount={offlineHatches} onClose={dismissOfflineReport}/>
    <ScrollView contentContainerStyle={[styles.content,mobile&&styles.contentMobile]} showsVerticalScrollIndicator={false}>
      <View style={styles.maxWidth}><CapitalHeader cash={state.cash} section="Farm" subtitle="Care · Grow · Compound"/>

      <View style={[styles.levelConsole,mobile&&styles.levelConsoleMobile]}>
        <View style={[styles.levelBadge,mobile&&styles.levelBadgeMobile]}><PixelText style={styles.levelLabel}>FUND LEVEL</PixelText><PixelText style={styles.levelValue}>{state.level}</PixelText></View>
        <View style={styles.xpConsole}><View style={[styles.xpTop,narrow&&styles.xpTopMobile]}><PixelText style={styles.xpLabel}>EXPERIENCE</PixelText><PixelText style={styles.xpValue}>{state.xp} / {xpForNextLevel(state.level)} XP</PixelText></View><View style={styles.xpTrack}><View style={[styles.xpFill,{width:`${xpPct}%`}]}><View style={styles.xpShine}/></View></View></View>
        <View style={[styles.healthBadge,mobile&&styles.healthBadgeMobile]}><PixelText style={styles.levelLabel}>OPS</PixelText><PixelText style={[styles.healthValue,health<65&&styles.healthBad]}>{health}%</PixelText></View>
      </View>

      <View style={[styles.briefingRow,!mobile&&styles.briefingRowDesktop]}><View style={styles.briefingMission}><MissionPanel state={state} onClaim={claimMission}/></View><View style={styles.briefingDaily}><DailyRewardCard state={state} onClaim={claimDailyReward}/></View></View>

      <View style={styles.tankSection}>
        <View style={[styles.sectionPlaque,mobile&&styles.sectionPlaqueMobile]}><View style={styles.plaqueBolt}/><PixelText style={[styles.sectionPlaqueText,mobile&&styles.sectionPlaqueTextMobile]}>THE OPERATING TANK</PixelText><View style={[styles.plaqueBolt,{right:8,left:undefined}]}/></View>
        <View style={styles.tankWrap}>
          <Tank population={state.shrimp} accessoryPopulation={state.shrimpAccessories} capacity={state.tankCapacity} upgrades={state.upgrades} placedDecor={placedDecor} onPress={hatchNow} onJumpState={setJumpingShrimp}/>
          <View pointerEvents="none" style={styles.overlayClip}>{isNight&&<View style={[StyleSheet.absoluteFillObject,styles.nightTint]}/>} {tintOpacity>0&&<View style={[StyleSheet.absoluteFillObject,{backgroundColor:tintColor,opacity:tintOpacity}]}/>} {state.conditions.waterQuality<62&&<><View style={[styles.grime,{left:'15%',top:'38%'}]}/><View style={[styles.grime,{right:'19%',top:'60%',width:10}]}/></>}</View>
          {showTankEvent&&feedingFrenzy&&<View pointerEvents="none" style={styles.overlayClip}><View style={styles.eventPlaque}><PixelText style={styles.eventPlaqueText}>FEEDING FRENZY</PixelText></View>{[22,37,51,66,78].map((left,i)=><View key={left} style={[styles.foodPellet,{left:`${left}%` as `${number}%`,top:18+(i%3)*7}]}/>)}</View>}
          {showTankEvent&&ambientEvent==='power'&&<View pointerEvents="none" style={[styles.overlayClip,styles.powerFailure]}><View style={styles.bigEventCard}><PixelText style={styles.eventHeadline}>⚠ POWER FAILURE</PixelText><PixelText style={styles.eventSub}>BACKUP SYSTEMS NEGOTIATING TERMS</PixelText></View></View>}
          {showTankEvent&&ambientEvent==='inspection'&&<View pointerEvents="none" style={[styles.inspectionEvent,mobile&&styles.inspectionEventMobile]}><Ionicons name="clipboard" size={19} color={colors.cream}/><View style={styles.eventCopy}><PixelText style={styles.eventHeadline}>SURPRISE INSPECTION</PixelText><PixelText style={styles.eventSub}>ACT NATURAL · HIDE THE OFFSHORE ALGAE</PixelText></View></View>}
          {showTankEvent&&ambientEvent==='visitor'&&<View pointerEvents="none" style={[styles.visitor,mobile&&styles.visitorMobile]}><PixelText style={styles.visitorText}>WHALE ANALYST VISITING</PixelText></View>}
          {showTankEvent&&ambientEvent==='treasure'&&<View pointerEvents="none" style={styles.treasure}><View style={styles.treasureLid}/><View style={styles.treasureBox}/><PixelText style={styles.treasureLabel}>UNEXPLAINED ASSETS</PixelText></View>}
          {!jumpingShrimp&&<View pointerEvents="none" style={[styles.timeBadge,mobile&&styles.timeBadgeMobile]}><Ionicons name={isNight?'moon':'sunny'} size={13} color={isNight?'#B9C8FF':colors.goldLight}/><PixelText style={styles.timeText}>{isNight?'NIGHT DESK':'DAY SESSION'}</PixelText></View>}
        </View>
        <View style={[styles.productionConsole,mobile&&styles.productionConsoleMobile]}><View style={styles.productionLeft}><View style={[styles.liveLamp,health<65&&styles.liveLampDanger]}/><PixelText style={styles.productionLabel}>{tankFull?'CAPACITY REACHED · SELL OR EXPAND':`NEXT AUTO-HATCH · ${nextHatch}s`}</PixelText></View>{!mobile&&<View style={styles.productionDivider}/>}<PixelText style={[styles.productionRate,conditionRate<80&&styles.productionRateDanger]}>OUTPUT {conditionRate}%</PixelText></View>
      </View>

      <View style={styles.statusStrip}><View style={[styles.statusChip,mobile&&styles.statusChipMobile]}><PixelText style={styles.statusLabel}>HEADQUARTERS</PixelText><PixelText style={styles.statusValue}>{biomeNames[biome]}</PixelText></View>{selectedLineage>0&&<View style={[styles.statusChip,mobile&&styles.statusChipMobile]}><PixelText style={styles.statusLabel}>GENETICS</PixelText><PixelText style={styles.statusValue}>{lineageLabel(selectedLineage)} · +{Math.round((lineageMultiplier(state,current.id)-1)*100)}%</PixelText></View>}{state.ipoCount>0&&<View style={[styles.statusChip,mobile&&styles.statusChipMobile]}><PixelText style={styles.statusLabel}>PUBLIC COMPANY</PixelText><PixelText style={styles.statusValue}>{state.prestigeShares} FOUNDER SHARES</PixelText></View>}</View>

      <TankConditionPanel state={state} onFeed={handleFeed} onService={service}/>
      <StockBrowser state={state} selectedId={state.selectedSpecies} onSelect={selectSpecies} onInspect={setInspectId}/>

      {inspected&&<View style={styles.inspectorOuter}><View style={[styles.inspector,mobile&&styles.inspectorMobile]}><Pressable accessibilityRole="button" accessibilityLabel="Close shrimp personnel file" onPress={()=>setInspectId(null)} style={styles.inspectClose}><Ionicons name="close" size={18} color={colors.cream}/></Pressable><View style={[styles.inspectPortrait,mobile&&styles.inspectPortraitMobile]}><View style={styles.inspectWater}/><PixelShrimp color={inspected.color} accentColor={inspected.accentColor} pattern={inspected.pattern} trait={inspected.trait} accessory={inspectAccessory} size={Math.min(112,Math.round(78*(inspected.displayScale??1)))}/></View><View style={[styles.inspectInfo,mobile&&styles.inspectInfoMobile]}><PixelText style={styles.inspectKicker}>SHRIMP PERSONNEL FILE</PixelText><PixelText style={styles.inspectName}>{inspected.name.toUpperCase()}</PixelText><View style={styles.inspectRule}/><PixelText style={styles.inspectLine}>{inspected.rarity.toUpperCase()} · AGE {1+inspectSeed%41} DAYS · {state.mutations[inspected.id]??0} MUTATIONS</PixelText><PixelText style={styles.inspectLine}>DESK: {['AUDIT','EQUITIES','M&A','FIXED INCOME'][inspectSeed%4]} · LINEAGE {state.lineage[inspected.id]??0}</PixelText><PixelText style={styles.inspectLine}>LIFETIME P&L ${(inspected.basePrice*(2+inspectSeed%7)).toLocaleString()}</PixelText>{inspected.legend&&<PixelText style={styles.inspectLegend}>{inspected.legend}</PixelText>}</View></View></View>}

      <View style={styles.sellOuter}><View style={[styles.sellCard,mobile&&styles.sellCardMobile]}><View style={styles.sellCopy}><PixelText style={styles.sellKicker}>TRADING DESK</PixelText><PixelText style={styles.sellTitle}>SELL {current.name.toUpperCase()}</PixelText><PixelText style={styles.sellDetail}>{state.shrimp[current.id]??0} READY · +{saleXpFor(current.id)} XP PER SALE</PixelText></View><Pressable accessibilityRole="button" disabled={(state.shrimp[current.id]??0)<1} onPress={()=>sellOne(current.id)} style={({pressed})=>[styles.sellButton,mobile&&styles.sellButtonMobile,(state.shrimp[current.id]??0)<1&&styles.sellDisabled,pressed&&styles.sellPressed]}><Ionicons name="cash" size={20} color={colors.ink}/><View><PixelText style={styles.sellButtonSmall}>EXECUTE</PixelText><PixelText style={styles.sellButtonText}>${salePrice.toLocaleString()}</PixelText></View></Pressable></View></View>
      </View>
    </ScrollView>
  </LinearGradient>;
}

const styles=StyleSheet.create({
  page:{flex:1},content:{padding:14,paddingBottom:118},contentMobile:{padding:8,paddingBottom:110},maxWidth:{width:'100%',maxWidth:1400,alignSelf:'center',gap:14},
  levelConsole:{backgroundColor:'#071B23',borderWidth:2,borderColor:colors.brass,padding:4,flexDirection:'row',alignItems:'stretch',gap:4},levelConsoleMobile:{flexWrap:'wrap'},
  levelBadge:{width:92,backgroundColor:'#0D313B',borderWidth:1,borderColor:'#315863',alignItems:'center',justifyContent:'center',padding:9},levelBadgeMobile:{width:84},levelLabel:{fontSize:12,color:colors.muted,letterSpacing:.35},levelValue:{fontFamily:'PressStart2P',fontSize:13,color:colors.goldLight,marginTop:6},
  xpConsole:{flex:1,minWidth:190,backgroundColor:'#0A2832',borderWidth:1,borderColor:'#315863',padding:10},xpTop:{flexDirection:'row',justifyContent:'space-between',gap:8},xpTopMobile:{flexDirection:'column',gap:2},xpLabel:{fontSize:12,color:colors.aqua},xpValue:{fontSize:13,color:colors.cream},xpTrack:{height:14,backgroundColor:'#04151B',borderWidth:2,borderColor:'#2D5058',marginTop:8,overflow:'hidden'},xpFill:{height:'100%',backgroundColor:colors.gold,position:'relative'},xpShine:{position:'absolute',left:0,right:0,top:1,height:2,backgroundColor:'#FFF4AA88'},
  healthBadge:{width:84,backgroundColor:'#0D313B',borderWidth:1,borderColor:'#315863',alignItems:'center',justifyContent:'center',padding:8},healthBadgeMobile:{width:80},healthValue:{fontFamily:'PressStart2P',fontSize:11,color:colors.success,marginTop:6},healthBad:{color:colors.danger},
  briefingRow:{gap:10},briefingRowDesktop:{flexDirection:'row'},briefingMission:{flex:1},briefingDaily:{flex:1},tankSection:{gap:0},
  sectionPlaque:{alignSelf:'center',minWidth:280,backgroundColor:'#151A1F',borderWidth:3,borderColor:colors.brass,paddingVertical:8,paddingHorizontal:26,alignItems:'center',position:'relative',zIndex:20,marginBottom:-4},sectionPlaqueMobile:{minWidth:0,width:'84%',paddingHorizontal:16},plaqueBolt:{position:'absolute',left:8,top:12,width:6,height:6,backgroundColor:colors.goldLight},sectionPlaqueText:{fontFamily:'PressStart2P',fontSize:10,color:colors.goldLight},sectionPlaqueTextMobile:{fontSize:10},
  tankWrap:{position:'relative',overflow:'visible',marginTop:10},overlayClip:{position:'absolute',left:0,right:0,top:0,bottom:0,overflow:'hidden'},nightTint:{backgroundColor:'#111943',opacity:.14},grime:{position:'absolute',width:7,height:7,backgroundColor:'#A7A75B',opacity:.2},eventPlaque:{alignSelf:'center',marginTop:50,backgroundColor:'#151A1F',borderWidth:2,borderColor:colors.gold,padding:9},eventPlaqueText:{fontFamily:'PressStart2P',fontSize:10,color:colors.goldLight},foodPellet:{position:'absolute',width:5,height:7,backgroundColor:'#D39551',borderWidth:1,borderColor:'#6E4927'},powerFailure:{backgroundColor:'#02080BCC',alignItems:'center',justifyContent:'center'},bigEventCard:{backgroundColor:'#1B1414',borderWidth:3,borderColor:colors.danger,padding:16,alignItems:'center',maxWidth:'84%'},
  inspectionEvent:{position:'absolute',alignSelf:'center',bottom:92,flexDirection:'row',gap:10,alignItems:'center',backgroundColor:'#3E2220EE',borderWidth:3,borderColor:colors.coral,padding:12,maxWidth:'76%'},inspectionEventMobile:{left:12,right:12,bottom:84,maxWidth:undefined},eventCopy:{flexShrink:1},eventHeadline:{fontFamily:'PressStart2P',color:colors.cream,fontSize:10},eventSub:{color:'#F0DED0',fontSize:12,marginTop:4},visitor:{position:'absolute',right:34,bottom:100,backgroundColor:'#0D3045EE',borderWidth:2,borderColor:'#6FA8C8',padding:10},visitorMobile:{right:12,bottom:90},visitorText:{fontSize:12,color:'#D4EFF9'},
  treasure:{position:'absolute',right:92,bottom:76,alignItems:'center'},treasureLid:{width:33,height:10,borderWidth:3,borderColor:'#543416',backgroundColor:'#B27B35'},treasureBox:{width:38,height:22,borderWidth:3,borderColor:'#543416',backgroundColor:'#8C5E2C'},treasureLabel:{color:colors.goldLight,fontSize:12,marginTop:3,backgroundColor:'#071A22DD',padding:4},timeBadge:{position:'absolute',left:15,top:32,flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#071A22E8',paddingHorizontal:9,paddingVertical:7,borderWidth:2,borderColor:'#4E7580'},timeBadgeMobile:{left:10,top:30,paddingHorizontal:7},timeText:{color:'#D5E7E8',fontSize:12},
  productionConsole:{backgroundColor:'#071C24',borderWidth:2,borderColor:colors.brass,borderTopWidth:0,paddingVertical:11,paddingHorizontal:13,flexDirection:'row',alignItems:'center',gap:8},productionConsoleMobile:{alignItems:'stretch',flexDirection:'column',gap:5},productionLeft:{flex:1,flexDirection:'row',alignItems:'center',gap:8},liveLamp:{width:9,height:9,backgroundColor:colors.success,borderWidth:1,borderColor:'#C1F1CA'},liveLampDanger:{backgroundColor:colors.danger,borderColor:'#FFC0B7'},productionLabel:{color:colors.aqua,fontSize:12,flex:1},productionDivider:{width:2,height:20,backgroundColor:colors.brass},productionRate:{color:colors.muted,fontSize:12},productionRateDanger:{color:colors.danger},
  statusStrip:{flexDirection:'row',flexWrap:'wrap',gap:7},statusChip:{backgroundColor:'#0A2730',borderWidth:2,borderColor:'#335762',paddingHorizontal:11,paddingVertical:9},statusChipMobile:{flexGrow:1,minWidth:'48%'},statusLabel:{fontSize:12,color:colors.muted},statusValue:{fontSize:13,color:colors.cream,marginTop:3},
  inspectorOuter:{backgroundColor:'#071B23',borderWidth:2,borderColor:colors.brass,padding:4},inspector:{backgroundColor:'#E7D7AE',borderWidth:2,borderColor:'#9F8351',padding:14,flexDirection:'row',alignItems:'center',gap:14,position:'relative'},inspectorMobile:{flexDirection:'column',alignItems:'stretch',paddingTop:46},inspectClose:{position:'absolute',right:8,top:8,zIndex:3,width:36,height:36,backgroundColor:'#152D35',borderWidth:2,borderColor:colors.brass,alignItems:'center',justifyContent:'center'},inspectPortrait:{width:132,height:108,backgroundColor:'#0B3544',borderWidth:3,borderColor:'#7C663F',alignItems:'center',justifyContent:'center',overflow:'hidden'},inspectPortraitMobile:{width:'100%',height:140},inspectWater:{position:'absolute',left:0,right:0,bottom:0,height:30,backgroundColor:'#1A6575'},inspectInfo:{flex:1,paddingRight:20},inspectInfoMobile:{paddingRight:0},inspectKicker:{color:'#56706F',fontSize:12,letterSpacing:.4},inspectName:{fontFamily:'PressStart2P',color:'#202B2B',fontSize:10,marginTop:6},inspectRule:{height:2,backgroundColor:'#A88E5D',marginVertical:8},inspectLine:{color:'#405B5E',fontSize:13,lineHeight:18},inspectLegend:{color:'#6D5842',fontSize:13,lineHeight:18,marginTop:5},
  sellOuter:{backgroundColor:'#071B23',borderWidth:2,borderColor:colors.brass,padding:4},sellCard:{backgroundColor:'#E7D7AE',borderWidth:2,borderColor:'#9F8351',padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12},sellCardMobile:{flexDirection:'column',alignItems:'stretch'},sellCopy:{flex:1},sellKicker:{color:'#6B6C58',fontSize:12},sellTitle:{fontFamily:'PressStart2P',color:'#1E2A2B',fontSize:10,marginTop:5,lineHeight:17},sellDetail:{color:'#4B666A',fontSize:13,marginTop:6},sellButton:{backgroundColor:colors.gold,paddingVertical:11,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8,borderWidth:2,borderColor:colors.goldLight,borderBottomWidth:5,borderBottomColor:colors.brassDark,minHeight:52},sellButtonMobile:{width:'100%',minHeight:58},sellButtonSmall:{color:'#624918',fontSize:12},sellButtonText:{color:colors.ink,fontFamily:'PressStart2P',fontSize:10,marginTop:3},sellDisabled:{opacity:.35},sellPressed:{transform:[{translateY:3}],borderBottomWidth:2},
});
