import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import React from 'react';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { PixelText } from '../components/PixelText';
import { upgrades } from '../game/catalog';
import { decorItems, DecorCategory } from '../game/decor';
import { useGame } from '../game/GameProvider';
import { tankHealth, upgradeCost } from '../game/engine';
import { colors } from '../theme/colors';

const categories: DecorCategory[] = ['Office Furniture','Finance Props','Executive Decor','Wall Street Jokes'];

function EquipmentPreview({ id, level }: { id: string; level: number }) {
  if (id==='filter') return <View style={styles.preview}><View style={styles.pipe}/><View style={styles.canister}/>{level>=2&&<View style={[styles.canister,{left:25,height:29}]}/>} {level>=4&&<View style={styles.gauge}/>}</View>;
  if (id==='heater') return <View style={styles.preview}><View style={styles.heater}/>{level>=2&&<View style={styles.console}/>} {level>=4&&<View style={styles.radiatorMini}/>}</View>;
  if (id==='algae') return <View style={styles.preview}><View style={styles.tray}/><View style={styles.greenPatch}/>{level>=3&&<View style={styles.hopper}/>}</View>;
  if (id==='oxygen') return <View style={styles.preview}><View style={styles.pump}/><View style={styles.bubbleMini}/><View style={[styles.bubbleMini,{left:30,top:4}]}/></View>;
  if (id==='breeding-lab') return <View style={styles.preview}><View style={styles.incubatorMini}><View style={styles.eggMini}/></View><View style={styles.labLampMini}/></View>;
  if (id==='compliance') return <View style={styles.preview}><View style={styles.deskMini}/><View style={styles.clipMini}/></View>;
  if (id==='terminal') return <View style={styles.preview}><View style={styles.screenMini}><PixelText style={styles.screenMiniText}>▲$</PixelText></View></View>;
  if (id==='lighting') return <View style={styles.preview}><View style={styles.lightBarMini}/><View style={styles.lightConeMini}/></View>;
  if (id==='generator') return <View style={styles.preview}><View style={styles.generatorMini}><View style={styles.dotMini}/></View></View>;
  if (id==='showcase') return <View style={styles.preview}><View style={styles.caseMini}/><View style={styles.pedestalMini}/></View>;
  return <View style={styles.preview}><View style={styles.armMini}/><View style={styles.netMini}/></View>;
}

export function MarketScreen() {
  const { state, buyUpgrade, expandTank, ownedDecor, placedDecor, buyDecor, placeDecor } = useGame();
  const tankCost = Math.round(75 * Math.pow(1.45, Math.max(0,(state.tankCapacity-20)/10)));
  const health=tankHealth(state);
  return <LinearGradient colors={[colors.ink,colors.deep]} style={styles.page}>
    <ScrollView contentContainerStyle={styles.content}>
      <PixelText style={styles.eyebrow}>REINVEST YOUR GAINS</PixelText><PixelText style={styles.title}>The Shrimp Exchange</PixelText>
      <View style={styles.balance}><View><PixelText style={styles.balanceLabel}>BUYING POWER</PixelText><PixelText style={styles.balanceSub}>OPERATIONS HEALTH {health}/100</PixelText></View><PixelText style={styles.balanceValue}>${state.cash.toLocaleString()}</PixelText></View>

      <View style={styles.sectionHeader}><PixelText style={styles.section}>EQUIPMENT</PixelText><PixelText style={styles.sectionHint}>EVERY PURCHASE CHANGES THE TANK</PixelText></View>
      <View style={styles.grid}>{upgrades.map((item)=>{const owned=state.upgrades[item.id]??0;const cost=upgradeCost(item.baseCost,owned);const affordable=state.cash>=cost;return <View key={item.id} style={[styles.card,affordable&&styles.cardAffordable]}>
        <View style={styles.previewBox}><EquipmentPreview id={item.id} level={owned}/></View>
        <View style={styles.cardMain}><View style={styles.nameRow}><PixelText style={styles.name}>{item.name}</PixelText>{owned>0&&<View style={styles.levelBadge}><PixelText style={styles.levelBadgeText}>LV {owned}</PixelText></View>}</View><PixelText style={styles.detail}>{item.detail}</PixelText><View style={styles.pips}>{Array.from({length:5},(_,i)=><View key={i} style={[styles.pip,i<Math.min(5,owned)&&styles.pipActive]}/>)}</View></View>
        <Pressable disabled={!affordable} onPress={()=>buyUpgrade(item.id)} style={({pressed})=>[styles.buy,!affordable&&styles.disabled,pressed&&affordable&&styles.buyPressed]}><PixelText style={styles.buyHint}>{owned===0?'INSTALL':'UPGRADE'}</PixelText><PixelText style={styles.buyText}>${cost.toLocaleString()}</PixelText></Pressable>
      </View>;})}</View>

      <PixelText style={styles.section}>REAL ESTATE</PixelText>
      <View style={[styles.card,state.cash>=tankCost&&styles.cardAffordable]}><View style={[styles.previewBox,styles.realEstatePreview]}><Ionicons name="business" size={25} color={colors.coral}/></View><View style={styles.cardMain}><PixelText style={styles.name}>Tank Expansion</PixelText><PixelText style={styles.detail}>+10 capacity · lowers crowding pressure · Current {state.tankCapacity}</PixelText><View style={styles.capacityTrack}><View style={[styles.capacityFill,{width:`${Math.min(100,state.tankCapacity/120*100)}%`}]} /></View></View><Pressable disabled={state.cash<tankCost} onPress={expandTank} style={({pressed})=>[styles.buy,styles.expandBuy,state.cash<tankCost&&styles.disabled,pressed&&state.cash>=tankCost&&styles.buyPressed]}><PixelText style={styles.buyHint}>EXPAND</PixelText><PixelText style={styles.buyText}>${tankCost.toLocaleString()}</PixelText></Pressable></View>

      <View style={styles.sectionHeader}><PixelText style={styles.section}>OFFICE DECOR</PixelText><PixelText style={styles.sectionHint}>BUY IT · PLACE IT · BUILD YOUR SHRIMP HQ</PixelText></View>
      <View style={styles.slotSummary}><PixelText style={styles.slotSummaryTitle}>PLACEMENT SLOTS</PixelText><PixelText style={styles.slotSummaryText}>Floor L / C / R · Wall L / C / R · Ceiling · Corner</PixelText></View>
      {categories.map(category=><View key={category} style={styles.decorGroup}><PixelText style={styles.decorGroupTitle}>{category.toUpperCase()}</PixelText><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.decorRow}>{decorItems.filter(item=>item.category===category).map(item=>{const owned=!!ownedDecor[item.id];const equipped=placedDecor[item.slot]===item.id;const locked=state.level<item.unlockLevel;const affordable=state.cash>=item.price;return <View key={item.id} style={[styles.decorCard,equipped&&styles.decorEquipped,locked&&styles.decorLocked]}><View style={styles.decorIcon}><Ionicons name={item.icon as any} size={20} color={equipped?colors.gold:colors.aqua}/></View><PixelText style={styles.decorName}>{item.name}</PixelText><PixelText style={styles.decorSlot}>{item.slot.replace('-',' ').toUpperCase()}</PixelText>{item.buff&&<PixelText style={styles.decorBuff}>{item.buff}</PixelText>}<View style={styles.decorSpacer}/>{locked?<PixelText style={styles.lockText}>UNLOCK LV. {item.unlockLevel}</PixelText>:owned?<Pressable onPress={()=>placeDecor(item.id)} style={[styles.decorButton,equipped&&styles.decorButtonEquipped]}><PixelText style={styles.decorButtonText}>{equipped?'PLACED':'PLACE'}</PixelText></Pressable>:<Pressable disabled={!affordable} onPress={()=>buyDecor(item.id)} style={[styles.decorButton,!affordable&&styles.disabled]}><PixelText style={styles.decorButtonText}>BUY ${item.price}</PixelText></Pressable>}</View>;})}</ScrollView></View>)}

      <View style={styles.memo}><PixelText style={styles.memoTag}>DESIGN DESK</PixelText><PixelText style={styles.memoTitle}>Your tank is now the office.</PixelText><PixelText style={styles.memoBody}>Functional upgrades grow into visible machinery. Decor is purchased separately and occupies real placement slots, so the aquarium gradually becomes a personalized underwater finance headquarters.</PixelText></View>
    </ScrollView>
  </LinearGradient>;
}

const styles=StyleSheet.create({
  page:{flex:1},content:{padding:20,paddingBottom:120},eyebrow:{color:colors.coral,fontSize:10,letterSpacing:2,marginTop:5},title:{fontSize:27,marginTop:5,marginBottom:18},balance:{padding:18,backgroundColor:colors.panel,borderRadius:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:'#285965'},balanceLabel:{fontSize:11,color:colors.muted},balanceSub:{color:colors.aqua,fontSize:7,marginTop:5},balanceValue:{fontSize:24,color:colors.gold},sectionHeader:{marginTop:25,marginBottom:9,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},section:{fontSize:11,letterSpacing:1.7,marginTop:24,marginBottom:9,color:colors.aqua},sectionHeader:{marginTop:4,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionHint:{fontSize:6,color:colors.muted,letterSpacing:.8},grid:{gap:8},card:{minHeight:92,flexDirection:'row',alignItems:'center',padding:11,backgroundColor:colors.panel,borderRadius:13,borderWidth:1,borderBottomWidth:4,borderColor:'#26525C',borderBottomColor:'#09252D'},cardAffordable:{borderColor:'#39717B'},previewBox:{width:68,height:60,borderRadius:10,backgroundColor:'#0A2933',borderWidth:1,borderColor:'#1F5260',alignItems:'center',justifyContent:'center',overflow:'hidden'},realEstatePreview:{borderColor:'#68463F'},cardMain:{flex:1,marginLeft:11,marginRight:8},nameRow:{flexDirection:'row',alignItems:'center',gap:6},name:{fontSize:10,flexShrink:1},detail:{color:colors.muted,fontSize:6,lineHeight:10,marginTop:4},levelBadge:{backgroundColor:'#204E58',borderRadius:5,paddingHorizontal:5,paddingVertical:3},levelBadgeText:{color:colors.aqua,fontSize:6},pips:{flexDirection:'row',gap:3,marginTop:7},pip:{width:13,height:4,borderRadius:2,backgroundColor:'#23434B'},pipActive:{backgroundColor:colors.aqua},buy:{minWidth:72,backgroundColor:colors.gold,borderRadius:9,paddingVertical:8,paddingHorizontal:9,alignItems:'center',borderBottomWidth:4,borderBottomColor:'#A87320'},expandBuy:{backgroundColor:'#FFB65C'},buyHint:{color:'#6C501B',fontSize:6,marginBottom:2},buyText:{color:colors.ink,fontSize:9},buyPressed:{transform:[{translateY:2}],borderBottomWidth:2},disabled:{opacity:.3,borderBottomWidth:1},capacityTrack:{height:5,borderRadius:3,backgroundColor:'#23434B',overflow:'hidden',marginTop:7},capacityFill:{height:'100%',backgroundColor:colors.coral},
  preview:{width:55,height:45,position:'relative'},pipe:{position:'absolute',right:5,top:0,width:7,height:29,backgroundColor:'#718C8D'},canister:{position:'absolute',right:3,bottom:0,width:19,height:32,backgroundColor:'#42646B',borderWidth:2,borderColor:'#19333A'},gauge:{position:'absolute',left:7,top:5,width:14,height:14,borderRadius:7,backgroundColor:'#E6DDB9',borderWidth:2,borderColor:'#98743F'},heater:{position:'absolute',left:7,top:2,width:8,height:39,backgroundColor:'#F07B49',borderWidth:2,borderColor:'#5A3730'},console:{position:'absolute',left:20,top:4,width:24,height:14,backgroundColor:'#31515A'},radiatorMini:{position:'absolute',left:22,bottom:3,width:28,height:18,borderTopWidth:6,borderBottomWidth:6,borderColor:'#825546'},tray:{position:'absolute',left:3,bottom:3,width:45,height:8,backgroundColor:'#77563D'},greenPatch:{position:'absolute',left:6,bottom:10,width:28,height:13,borderRadius:8,backgroundColor:'#50A659'},hopper:{position:'absolute',right:2,bottom:10,width:11,height:24,backgroundColor:'#69767A'},pump:{position:'absolute',left:3,bottom:3,width:24,height:18,backgroundColor:'#426771',borderWidth:2,borderColor:'#17323A'},bubbleMini:{position:'absolute',left:18,top:14,width:7,height:7,borderRadius:4,borderWidth:2,borderColor:'#9DE5E4'},incubatorMini:{position:'absolute',left:8,bottom:2,width:28,height:38,backgroundColor:'#385863',borderWidth:2,borderColor:'#17333A',padding:4},eggMini:{width:7,height:10,borderRadius:4,backgroundColor:'#F0E5C4',alignSelf:'center',marginTop:10},labLampMini:{position:'absolute',right:4,bottom:8,width:13,height:4,backgroundColor:'#E0C766'},deskMini:{position:'absolute',left:3,bottom:3,width:47,height:12,backgroundColor:'#74513A'},clipMini:{position:'absolute',left:7,bottom:14,width:14,height:22,backgroundColor:'#EFE3C0',borderWidth:2,borderColor:'#83745A'},screenMini:{position:'absolute',left:7,top:4,width:41,height:29,backgroundColor:'#071A22',borderWidth:3,borderColor:'#49666D',alignItems:'center',justifyContent:'center'},screenMiniText:{fontSize:7,color:'#75E997'},lightBarMini:{position:'absolute',left:3,top:3,width:49,height:6,backgroundColor:'#C5A04F'},lightConeMini:{position:'absolute',left:14,top:9,width:29,height:30,backgroundColor:'#FFF2A422'},generatorMini:{position:'absolute',left:8,top:8,width:39,height:28,backgroundColor:'#535C5D',borderWidth:2,borderColor:'#263337'},dotMini:{width:5,height:5,borderRadius:3,backgroundColor:'#76EF8E',margin:5},caseMini:{position:'absolute',left:12,top:2,width:31,height:31,backgroundColor:'#9DEAE922',borderWidth:2,borderColor:'#D4AF58'},pedestalMini:{position:'absolute',left:18,bottom:0,width:21,height:11,backgroundColor:'#6B5136'},armMini:{position:'absolute',right:12,top:1,width:6,height:32,backgroundColor:'#788D91',transform:[{rotate:'23deg'}]},netMini:{position:'absolute',right:18,bottom:0,width:24,height:16,borderWidth:2,borderColor:'#AAC4C3'},
  slotSummary:{backgroundColor:'#0B2D36',borderRadius:10,padding:10,borderWidth:1,borderColor:'#24515C',marginBottom:6},slotSummaryTitle:{fontSize:7,color:colors.gold},slotSummaryText:{fontSize:6,color:colors.muted,marginTop:4},decorGroup:{marginTop:14},decorGroupTitle:{fontSize:8,color:colors.cream,letterSpacing:1.1,marginBottom:7},decorRow:{gap:9,paddingRight:20},decorCard:{width:138,minHeight:154,backgroundColor:'#123B47',borderRadius:13,padding:11,borderWidth:2,borderBottomWidth:4,borderColor:'#285C67',borderBottomColor:'#08252C'},decorEquipped:{borderColor:colors.gold,backgroundColor:'#164850'},decorLocked:{opacity:.4},decorIcon:{width:34,height:34,borderRadius:9,backgroundColor:'#092832',alignItems:'center',justifyContent:'center'},decorName:{fontSize:9,marginTop:8,lineHeight:13},decorSlot:{fontSize:5,color:colors.aqua,marginTop:5},decorBuff:{fontSize:5,color:colors.gold,marginTop:4},decorSpacer:{flex:1,minHeight:8},lockText:{fontSize:6,color:colors.muted},decorButton:{backgroundColor:colors.gold,borderRadius:7,paddingVertical:8,alignItems:'center',borderBottomWidth:3,borderBottomColor:'#A57322'},decorButtonEquipped:{backgroundColor:'#5A7868',borderBottomColor:'#344A40'},decorButtonText:{fontSize:7,color:colors.ink},memo:{marginTop:24,borderRadius:18,padding:19,backgroundColor:'#352646',borderWidth:2,borderColor:'#75599C'},memoTag:{color:'#CFB1FF',fontSize:8,letterSpacing:1.8},memoTitle:{fontSize:17,marginTop:7},memoBody:{color:'#CFBEDA',fontSize:9,lineHeight:15,marginTop:7}
});
