import { Ionicons } from '@expo/vector-icons';
import React from 'react';
import { Modal, Pressable, StyleSheet, View } from 'react-native';
import { colors } from '../theme/colors';
import { PixelText } from './PixelText';

export function OfflineReport({amount,onClose}:{amount:number;onClose:()=>void}){
  return <Modal transparent visible={amount>0} animationType="fade" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.outer} accessibilityRole="alert"><View style={styles.cornerTL}/><View style={styles.cornerTR}/><View style={styles.cornerBL}/><View style={styles.cornerBR}/><View style={styles.card}><View style={styles.icon}><Ionicons name="moon" size={28} color={colors.goldLight}/></View><PixelText style={styles.eyebrow}>OVERNIGHT OPERATIONS REPORT</PixelText><PixelText style={styles.title}>THE TANK STAYED BUSY</PixelText><View style={styles.rule}/><PixelText style={styles.amount}>+{amount} SHRIMP</PixelText><PixelText style={styles.body}>YOUR AQUATIC WORKFORCE KEPT COMPOUNDING WHILE MANAGEMENT WAS OFFLINE.</PixelText><Pressable onPress={onClose} style={({pressed})=>[styles.button,pressed&&styles.buttonPressed]}><PixelText style={styles.buttonSmall}>RECONCILE POSITION</PixelText><PixelText style={styles.buttonText}>COLLECT DIVIDENDS</PixelText></Pressable></View></View></View></Modal>;
}

const styles=StyleSheet.create({
  backdrop:{flex:1,backgroundColor:'rgba(2,10,14,.9)',alignItems:'center',justifyContent:'center',padding:26},outer:{width:'100%',maxWidth:430,backgroundColor:'#06171E',borderWidth:3,borderColor:colors.brass,padding:4,position:'relative',shadowColor:'#000',shadowOpacity:.65,shadowRadius:0,shadowOffset:{width:6,height:8}},card:{backgroundColor:'#0B2B35',borderWidth:2,borderColor:'#365F69',alignItems:'center',padding:22},icon:{width:58,height:58,backgroundColor:'#071B23',borderWidth:3,borderColor:colors.gold,alignItems:'center',justifyContent:'center',marginBottom:16},eyebrow:{fontSize:6,color:colors.aqua,letterSpacing:1.8},title:{fontFamily:'PressStart2P',fontSize:10,color:colors.goldLight,marginTop:9,textAlign:'center',lineHeight:17},rule:{width:'72%',height:2,backgroundColor:colors.brass,marginVertical:14},amount:{fontFamily:'PressStart2P',fontSize:17,color:colors.goldLight},body:{fontSize:8,lineHeight:13,color:colors.muted,textAlign:'center',marginTop:11,maxWidth:310},button:{width:'100%',backgroundColor:colors.gold,borderWidth:3,borderColor:colors.goldLight,borderBottomWidth:6,borderBottomColor:colors.brassDark,paddingVertical:10,alignItems:'center',marginTop:19},buttonPressed:{transform:[{translateY:4}],borderBottomWidth:2},buttonSmall:{fontSize:5,color:'#654816'},buttonText:{fontFamily:'PressStart2P',fontSize:7,color:colors.ink,marginTop:4},cornerTL:{position:'absolute',left:-5,top:-5,width:13,height:13,borderLeftWidth:4,borderTopWidth:4,borderColor:colors.goldLight,zIndex:5},cornerTR:{position:'absolute',right:-5,top:-5,width:13,height:13,borderRightWidth:4,borderTopWidth:4,borderColor:colors.goldLight,zIndex:5},cornerBL:{position:'absolute',left:-5,bottom:-5,width:13,height:13,borderLeftWidth:4,borderBottomWidth:4,borderColor:colors.goldLight,zIndex:5},cornerBR:{position:'absolute',right:-5,bottom:-5,width:13,height:13,borderRightWidth:4,borderBottomWidth:4,borderColor:colors.goldLight,zIndex:5},
});
