import React, { useEffect, useRef } from 'react';
import { Animated, Easing, StyleSheet, View } from 'react-native';
import { colors } from '../theme/colors';
import { PixelText } from './PixelText';

function Pulse({children,enabled=true,dy=2}:{children:React.ReactNode;enabled?:boolean;dy?:number}){const a=useRef(new Animated.Value(0)).current;useEffect(()=>{if(!enabled)return;const loop=Animated.loop(Animated.sequence([Animated.timing(a,{toValue:1,duration:900,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(a,{toValue:0,duration:900,easing:Easing.inOut(Easing.quad),useNativeDriver:true})]));loop.start();return()=>loop.stop();},[a,enabled]);if(!enabled)return <>{children}</>;return <Animated.View style={{opacity:a.interpolate({inputRange:[0,1],outputRange:[.75,1]}),transform:[{translateY:a.interpolate({inputRange:[0,1],outputRange:[0,-dy]})}]}}>{children}</Animated.View>}
function Blink({enabled=true,style}:{enabled?:boolean;style?:object}){const a=useRef(new Animated.Value(0)).current;useEffect(()=>{if(!enabled)return;const loop=Animated.loop(Animated.sequence([Animated.timing(a,{toValue:1,duration:330,useNativeDriver:true}),Animated.delay(900),Animated.timing(a,{toValue:.15,duration:180,useNativeDriver:true}),Animated.delay(650)]));loop.start();return()=>loop.stop();},[a,enabled]);return <Animated.View style={[s.blink,{opacity:enabled?a:1},style]}/>}

export function PixelDecor({id,animate=false,scale=1}:{id:string;animate?:boolean;scale?:number}){
  const wrap=(node:React.ReactNode)=><View style={[s.stage,{transform:[{scale}]}]}>{node}</View>;
  if(id==='desk')return wrap(<><View style={s.deskShadow}/><View style={s.deskTop}><View style={s.deskHighlight}/></View><View style={s.deskFront}><View style={s.drawer}/><View style={[s.drawer,{left:36}]}/></View><View style={s.deskLegL}/><View style={s.deskLegR}/><View style={s.paper}/><View style={s.pen}/></>);
  if(id==='chair')return wrap(<><View style={s.chairShadow}/><View style={s.chairBack}><View style={s.chairTuftA}/><View style={s.chairTuftB}/></View><View style={s.chairSeat}/><View style={s.chairStem}/><View style={s.chairBase}/><View style={s.wheelL}/><View style={s.wheelR}/></>);
  if(id==='filing')return wrap(<View style={s.fileBox}>{[0,1,2].map(i=><View key={i} style={s.fileDrawer}><View style={s.fileHandle}/><View style={s.fileLabel}/></View>)}</View>);
  if(id==='meeting')return wrap(<><View style={s.tableShadow}/><View style={s.tableTop}><View style={s.tableHighlight}/></View><View style={s.tableLeg}/><View style={[s.miniChair,{left:7}]}/><View style={[s.miniChair,{right:7}]}/></>);
  if(id==='copier')return wrap(<View style={s.copier}><View style={s.copierTop}/><View style={s.copierGlass}/><View style={s.copierTray}/><Blink enabled={animate} style={{right:7,top:18}}/><Pulse enabled={animate} dy={4}><View style={s.paperOut}/></Pulse></View>);
  if(id==='banker-lamp')return wrap(<><Pulse enabled={animate} dy={1}><View style={s.lampGlow}/></Pulse><View style={s.lampShade}><View style={s.lampHighlight}/></View><View style={s.lampStem}/><View style={s.lampBase}/></>);
  if(id==='coffee-cart')return wrap(<><View style={s.cartTop}/><View style={s.cartFront}><View style={s.cartPanel}/><View style={[s.cartPanel,{left:29}]}/></View><View style={s.cartLegL}/><View style={s.cartLegR}/><View style={s.mug}/></>);
  if(id==='water-cooler')return wrap(<><View style={s.bottle}><View style={s.bottleShine}/></View><View style={s.cooler}><View style={s.coolerTap}/><View style={s.coolerSlot}/></View></>);
  if(id==='trash')return wrap(<><View style={s.trashRim}/><View style={s.trash}><View style={s.trashLine}/><View style={[s.trashLine,{left:19}]}/></View></>);
  if(id==='conference-phone')return wrap(<><View style={s.phone}><View style={s.phoneSpeakerL}/><View style={s.phoneSpeakerR}/><View style={s.phoneScreen}/><View style={s.phoneButton}/></View></>);
  if(id==='ticker')return wrap(<View style={s.ticker}><Blink enabled={animate} style={{left:6,top:8}}/><PixelText style={s.tickerText}>SHRP ▲ 4.2   KRLL ▼ 1.1</PixelText><View style={s.tickerRail}/></View>);
  if(id==='terminal')return wrap(<><View style={s.monitor}><PixelText style={s.monitorText}>SHRP ▲</PixelText><View style={s.graphA}/><View style={s.graphB}/><Blink enabled={animate} style={{right:5,top:5}}/></View><View style={s.monitorStand}/><View style={s.keyboard}/></>);
  if(id==='chart')return wrap(<View style={s.poster}><View style={s.posterGridA}/><View style={s.posterGridB}/><View style={s.chartA}/><View style={s.chartB}/><View style={s.chartDot}/></View>);
  if(id==='pnl')return wrap(<View style={s.pnl}><PixelText style={s.pnlTitle}>P&L</PixelText><View style={s.greenBar}/><View style={s.greenBar2}/><View style={s.redBar}/><Blink enabled={animate} style={{right:5,top:5}}/></View>);
  if(id==='bull')return wrap(<><View style={s.bullBase}/><View style={s.bullBody}/><View style={s.bullHead}/><View style={s.bullLegA}/><View style={s.bullLegB}/><View style={s.hornL}/><View style={s.hornR}/><Pulse enabled={animate} dy={1}><View style={s.spark}/></Pulse></>);
  if(id==='briefcase')return wrap(<View style={s.case}><View style={s.caseHandle}/><View style={s.caseStripe}/><View style={s.caseLatch}/><View style={s.caseCornerL}/><View style={s.caseCornerR}/></View>);
  if(id==='vault'||id==='safe')return wrap(<View style={s.vault}><View style={s.vaultInset}><View style={s.vaultWheel}><View style={s.spokeH}/><View style={s.spokeV}/><View style={s.spokeD}/></View></View><View style={s.vaultHingeA}/><View style={s.vaultHingeB}/></View>);
  if(id==='abacus')return wrap(<View style={s.abacus}>{[0,1,2,3].map(r=><View key={r} style={[s.abacusRod,{top:8+r*10}]}>{[0,1,2,3,4].map(c=><View key={c} style={[s.bead,{left:5+c*9+(r%2)*3}]}/>)}</View>)}</View>);
  if(id==='clipboard')return wrap(<View style={s.clipboard}><View style={s.clip}/>{[15,23,31].map((top,i)=><View key={top} style={[s.clipLine,{top,width:i===2?22:29}]}/>)}</View>);
  if(id==='clock')return wrap(<View style={s.clock}><View style={s.clockInner}/><View style={s.handA}/><View style={s.handB}/><View style={s.clockPin}/></View>);
  if(id==='whiteboard')return wrap(<View style={s.whiteboard}><View style={s.wbGridA}/><View style={s.wbGridB}/><View style={s.wbA}/><View style={s.wbB}/><View style={s.wbDot}/><View style={s.wbTray}/></View>);
  if(id==='aum-display')return wrap(<View style={s.aum}><PixelText style={s.aumLabel}>AUM</PixelText><PixelText style={s.aumValue}>$12.8M</PixelText><View style={s.aumBar}/><Blink enabled={animate} style={{right:5,top:5}}/></View>);
  if(id==='nameplate')return wrap(<View style={s.nameplate}><View style={s.nameplateInner}><PixelText style={s.nameplateText}>CEO</PixelText></View></View>);
  if(id==='mahogany')return wrap(<View style={s.mahogany}><View style={s.woodFrame}/><View style={s.woodLineA}/><View style={s.woodLineB}/></View>);
  if(id==='brass-rail')return wrap(<><View style={s.railTop}/><View style={s.railPostL}/><View style={s.railPostC}/><View style={s.railPostR}/><View style={s.railFoot}/></>);
  if(id==='velvet-rope')return wrap(<><View style={s.ropePostL}/><View style={s.ropePostR}/><View style={s.ropeCapL}/><View style={s.ropeCapR}/><View style={s.ropeLine}/></>);
  if(id==='skyline')return wrap(<View style={s.skyline}>{[24,42,31,54,37,48].map((h,i)=><View key={i} style={[s.building,{height:h}]}>{[0,1,2].map(w=><View key={w} style={[s.window,{top:6+w*10}]}/>)}</View>)}</View>);
  if(id==='ceo-portrait')return wrap(<View style={s.portrait}><View style={s.portraitInner}><View style={s.portraitHead}/><View style={s.portraitBody}/><View style={s.portraitShirt}/><View style={s.portraitTie}/></View></View>);
  if(id==='chandelier')return wrap(<><View style={s.chandelierChain}/><View style={s.chandelierBar}/>{[14,39,64].map(left=><Pulse key={left} enabled={animate} dy={1}><View style={[s.bulb,{left}]}/></Pulse>)}</>);
  if(id==='visor-rack')return wrap(<View style={s.rack}><View style={s.rackRail}/>{[8,34,60].map((left,i)=><View key={left} style={[s.visor,{left,top:i===1?19:12}]}><View style={s.visorBill}/></View>)}</View>);
  if(id==='calculator')return wrap(<View style={s.calc}><View style={s.calcScreen}/><View style={s.calcGrid}>{Array.from({length:12},(_,i)=><View key={i} style={s.calcKey}/>)}</View></View>);
  if(id==='ledger')return wrap(<><View style={s.bookShadow}/><View style={s.bookA}/><View style={s.bookB}/><View style={s.page}/><View style={s.bookRibbon}/></>);
  if(id==='espresso')return wrap(<View style={s.espresso}><View style={s.espressoTop}/><View style={s.espressoGauge}/><View style={s.spout}/><View style={s.cup}/><Pulse enabled={animate} dy={6}><View style={s.steam}/></Pulse></View>);
  if(id==='opening-bell')return wrap(<><Pulse enabled={animate} dy={1}><View style={s.bellDome}><View style={s.bellHighlight}/></View></Pulse><View style={s.bellBase}/></>);
  if(id==='ticker-tape')return wrap(<View style={s.tape}><PixelText style={s.tapeText}>BUY · SELL · HOLD · MOLT</PixelText></View>);
  const label=id==='earnings'?'EARNINGS CALL':id==='buy-dip'?'BUY THE DIP':id==='compliance-sign'?'COMPLIANCE IS WATCHING':id==='liquidity-plaque'?'LIQUIDITY POOL':id==='private-equity'?'PRIVATE EQUITY PRAWNS':id==='shell-street-logo'?'SHELL STREET CAPITAL':id==='private-bank'?'PRIVATE AQUATIC BANK':'EXECUTIVE HQ';
  return wrap(<View style={s.sign}><View style={s.signInner}><PixelText style={s.signText}>{label}</PixelText></View></View>);
}

const s=StyleSheet.create({
  stage:{width:92,height:72,position:'relative',alignItems:'center',justifyContent:'center'},blink:{position:'absolute',width:5,height:5,backgroundColor:'#74F09A',borderWidth:1,borderColor:'#C7FFD4'},
  deskShadow:{position:'absolute',left:8,right:8,bottom:8,height:4,backgroundColor:'#03111855'},deskTop:{position:'absolute',left:8,top:22,width:76,height:10,backgroundColor:'#71442E',borderWidth:2,borderColor:'#2C1B14'},deskHighlight:{height:2,backgroundColor:'#B67D50'},deskFront:{position:'absolute',left:13,top:31,width:66,height:20,backgroundColor:'#523121',borderWidth:2,borderColor:'#2B1A13'},drawer:{position:'absolute',left:5,top:5,width:25,height:8,borderWidth:1,borderColor:'#8D6040',backgroundColor:'#633B27'},deskLegL:{position:'absolute',left:17,top:49,width:7,height:17,backgroundColor:'#3D271E'},deskLegR:{position:'absolute',right:17,top:49,width:7,height:17,backgroundColor:'#3D271E'},paper:{position:'absolute',left:18,top:15,width:26,height:7,backgroundColor:'#EFE1B8',borderWidth:1,borderColor:'#A69B7A'},pen:{position:'absolute',left:52,top:18,width:18,height:2,backgroundColor:'#6FA3C0',transform:[{rotate:'-8deg'}]},
  chairShadow:{position:'absolute',left:22,right:22,bottom:5,height:4,backgroundColor:'#03111855'},chairBack:{position:'absolute',top:7,width:39,height:30,backgroundColor:'#1D3038',borderWidth:3,borderColor:'#07171D'},chairTuftA:{position:'absolute',left:8,top:8,width:7,height:7,backgroundColor:'#344951'},chairTuftB:{position:'absolute',right:8,top:15,width:7,height:7,backgroundColor:'#344951'},chairSeat:{position:'absolute',top:39,width:43,height:11,backgroundColor:'#263F49',borderWidth:2,borderColor:'#0E252C'},chairStem:{position:'absolute',top:50,width:5,height:12,backgroundColor:'#859297'},chairBase:{position:'absolute',top:61,width:34,height:4,backgroundColor:'#637379'},wheelL:{position:'absolute',left:26,bottom:2,width:6,height:6,backgroundColor:'#111C20'},wheelR:{position:'absolute',right:26,bottom:2,width:6,height:6,backgroundColor:'#111C20'},
  fileBox:{width:45,height:61,backgroundColor:'#4D5E64',padding:5,gap:4,borderWidth:3,borderColor:'#1B2E34'},fileDrawer:{height:14,backgroundColor:'#78868B',borderWidth:2,borderColor:'#34454A',position:'relative'},fileHandle:{position:'absolute',left:11,top:5,width:12,height:3,backgroundColor:'#26363B'},fileLabel:{position:'absolute',right:4,top:4,width:7,height:5,backgroundColor:'#C8C0A4'},
  tableShadow:{position:'absolute',left:8,right:8,bottom:7,height:4,backgroundColor:'#03111855'},tableTop:{position:'absolute',left:6,top:27,width:80,height:12,backgroundColor:'#70452D',borderWidth:3,borderColor:'#2D1D15'},tableHighlight:{height:2,backgroundColor:'#B87A4D'},tableLeg:{position:'absolute',left:42,top:39,width:8,height:24,backgroundColor:'#493022'},miniChair:{position:'absolute',top:35,width:13,height:24,borderWidth:3,borderColor:'#304951',backgroundColor:'#17292F'},
  copier:{width:53,height:58,backgroundColor:'#BFC6C2',borderWidth:3,borderColor:'#4A5A5E',position:'relative'},copierTop:{height:12,backgroundColor:'#303F44',borderBottomWidth:2,borderBottomColor:'#66767A'},copierGlass:{position:'absolute',left:7,right:7,top:6,height:5,backgroundColor:'#75939A'},copierTray:{position:'absolute',left:10,bottom:8,width:31,height:18,backgroundColor:'#E7E9DE',borderWidth:2,borderColor:'#778483'},paperOut:{position:'absolute',left:11,top:-8,width:31,height:11,backgroundColor:'#FFF1C9',borderWidth:1,borderColor:'#A99C79'},
  lampGlow:{position:'absolute',left:20,top:9,width:51,height:28,backgroundColor:'#76FF9A18'},lampShade:{position:'absolute',top:12,left:25,width:42,height:16,backgroundColor:'#258153',borderWidth:3,borderColor:'#123D29',transform:[{skewX:'-12deg'}]},lampHighlight:{height:3,backgroundColor:'#7FD19E'},lampStem:{position:'absolute',left:44,top:28,width:5,height:28,backgroundColor:'#C3A44E'},lampBase:{position:'absolute',left:29,bottom:7,width:35,height:7,backgroundColor:'#8D6D32',borderWidth:1,borderColor:'#5F471F'},
  cartTop:{position:'absolute',left:10,top:18,width:72,height:10,backgroundColor:'#70452D',borderWidth:2,borderColor:'#2D1D15'},cartFront:{position:'absolute',left:16,top:28,width:60,height:24,backgroundColor:'#4A2D20',borderWidth:2,borderColor:'#261711'},cartPanel:{position:'absolute',left:5,top:5,width:22,height:12,borderWidth:1,borderColor:'#83583A'},cartLegL:{position:'absolute',left:20,top:52,width:5,height:14,backgroundColor:'#3B261C'},cartLegR:{position:'absolute',right:20,top:52,width:5,height:14,backgroundColor:'#3B261C'},mug:{position:'absolute',right:17,top:10,width:12,height:10,borderWidth:2,borderColor:'#EFE5C6'},
  bottle:{position:'absolute',top:4,width:27,height:29,backgroundColor:'#68C2D0',borderWidth:2,borderColor:'#B0F2F2'},bottleShine:{position:'absolute',left:5,top:4,width:5,height:17,backgroundColor:'#D7FFFF55'},cooler:{position:'absolute',top:32,width:40,height:34,backgroundColor:'#D9DFDA',borderWidth:3,borderColor:'#6A7979'},coolerTap:{position:'absolute',right:2,top:8,width:10,height:4,backgroundColor:'#2C5059'},coolerSlot:{position:'absolute',left:8,right:8,bottom:5,height:8,backgroundColor:'#ADB9B7'},
  trashRim:{position:'absolute',top:12,width:38,height:6,backgroundColor:'#75878C',borderWidth:2,borderColor:'#273B41'},trash:{position:'absolute',top:18,width:34,height:43,backgroundColor:'#4F6268',borderWidth:3,borderColor:'#26393E'},trashLine:{position:'absolute',left:9,top:5,bottom:5,width:3,backgroundColor:'#72858A'},
  phone:{width:57,height:31,backgroundColor:'#1C333C',borderWidth:3,borderColor:'#0B2027',position:'relative'},phoneSpeakerL:{position:'absolute',left:4,top:6,width:10,height:15,backgroundColor:'#324C55'},phoneSpeakerR:{position:'absolute',right:4,top:6,width:10,height:15,backgroundColor:'#324C55'},phoneScreen:{position:'absolute',left:21,top:7,width:15,height:8,backgroundColor:'#79BF98'},phoneButton:{position:'absolute',left:24,top:18,width:8,height:5,backgroundColor:'#84979A'},
  ticker:{width:90,height:30,backgroundColor:'#04151C',borderWidth:3,borderColor:'#A98138',justifyContent:'center',paddingHorizontal:7},tickerText:{fontSize:6,color:'#71E99D'},tickerRail:{position:'absolute',left:4,right:4,bottom:3,height:2,backgroundColor:'#6A4E20'},
  monitor:{width:62,height:45,backgroundColor:'#041319',borderWidth:4,borderColor:'#4A6066',padding:6,position:'relative'},monitorText:{fontSize:6,color:'#72E89A'},graphA:{position:'absolute',left:9,bottom:10,width:25,height:3,backgroundColor:'#65D990',transform:[{rotate:'-18deg'}]},graphB:{position:'absolute',left:30,bottom:16,width:18,height:3,backgroundColor:'#65D990',transform:[{rotate:'21deg'}]},monitorStand:{width:7,height:6,backgroundColor:'#6C797C',alignSelf:'center'},keyboard:{width:69,height:8,backgroundColor:'#46565B',borderWidth:1,borderColor:'#243439'},
  poster:{width:63,height:50,backgroundColor:'#E9DDBA',borderWidth:4,borderColor:'#5B422B',position:'relative'},posterGridA:{position:'absolute',left:6,right:6,top:15,height:1,backgroundColor:'#C1B69A'},posterGridB:{position:'absolute',left:6,right:6,top:30,height:1,backgroundColor:'#C1B69A'},chartA:{position:'absolute',left:8,bottom:11,width:29,height:4,backgroundColor:'#358A57',transform:[{rotate:'-24deg'}]},chartB:{position:'absolute',left:34,bottom:19,width:19,height:4,backgroundColor:'#358A57',transform:[{rotate:'22deg'}]},chartDot:{position:'absolute',right:6,top:6,width:6,height:6,backgroundColor:'#D9B14A'},
  pnl:{width:63,height:47,backgroundColor:'#092128',borderWidth:3,borderColor:'#A4813D',padding:6},pnlTitle:{fontFamily:'PressStart2P',fontSize:6,color:'#EED37F'},greenBar:{width:38,height:5,backgroundColor:'#5FD38A',marginTop:4},greenBar2:{width:28,height:5,backgroundColor:'#5FD38A',marginTop:3},redBar:{width:20,height:5,backgroundColor:'#D85C55',marginTop:3},
  bullBase:{position:'absolute',left:12,right:12,bottom:5,height:9,backgroundColor:'#60451F',borderWidth:2,borderColor:'#30210F'},bullBody:{position:'absolute',left:17,top:31,width:37,height:16,backgroundColor:'#B88732',borderWidth:2,borderColor:'#60451F'},bullHead:{position:'absolute',right:14,top:26,width:18,height:15,backgroundColor:'#C59B48',borderWidth:1,borderColor:'#60451F'},bullLegA:{position:'absolute',left:22,top:45,width:5,height:14,backgroundColor:'#775522'},bullLegB:{position:'absolute',left:45,top:45,width:5,height:14,backgroundColor:'#775522'},hornL:{position:'absolute',right:25,top:20,width:13,height:4,backgroundColor:'#E8D8A7',transform:[{rotate:'-28deg'}]},hornR:{position:'absolute',right:10,top:22,width:12,height:4,backgroundColor:'#E8D8A7',transform:[{rotate:'28deg'}]},spark:{position:'absolute',right:6,top:13,width:7,height:7,backgroundColor:'#FFE178',transform:[{rotate:'45deg'}]},
  case:{width:57,height:36,backgroundColor:'#C79A3C',borderWidth:3,borderColor:'#5D421C',position:'relative'},caseHandle:{position:'absolute',left:17,top:-11,width:20,height:11,borderWidth:3,borderBottomWidth:0,borderColor:'#926B29'},caseStripe:{position:'absolute',left:2,right:2,top:17,height:3,backgroundColor:'#7B5720'},caseLatch:{position:'absolute',left:24,top:13,width:8,height:8,backgroundColor:'#FFF0A2',borderWidth:1,borderColor:'#7A581F'},caseCornerL:{position:'absolute',left:2,bottom:2,width:8,height:7,borderLeftWidth:2,borderBottomWidth:2,borderColor:'#F0CC65'},caseCornerR:{position:'absolute',right:2,bottom:2,width:8,height:7,borderRightWidth:2,borderBottomWidth:2,borderColor:'#F0CC65'},
  vault:{width:61,height:61,borderRadius:31,backgroundColor:'#4B6067',borderWidth:6,borderColor:'#1E343B',padding:6,position:'relative'},vaultInset:{flex:1,borderRadius:24,borderWidth:2,borderColor:'#94A3A4',alignItems:'center',justifyContent:'center'},vaultWheel:{width:27,height:27,borderRadius:14,borderWidth:3,borderColor:'#D0AD62',position:'relative'},spokeH:{position:'absolute',left:2,top:10,width:17,height:3,backgroundColor:'#D0AD62'},spokeV:{position:'absolute',left:10,top:2,width:3,height:17,backgroundColor:'#D0AD62'},spokeD:{position:'absolute',left:4,top:9,width:15,height:3,backgroundColor:'#D0AD62',transform:[{rotate:'45deg'}]},vaultHingeA:{position:'absolute',right:-7,top:13,width:8,height:8,backgroundColor:'#89999C'},vaultHingeB:{position:'absolute',right:-7,bottom:13,width:8,height:8,backgroundColor:'#89999C'},
  abacus:{width:61,height:47,borderWidth:4,borderColor:'#653F25',backgroundColor:'#A87C46',position:'relative'},abacusRod:{position:'absolute',left:5,right:5,height:2,backgroundColor:'#452817'},bead:{position:'absolute',top:-4,width:6,height:8,backgroundColor:'#2F7085',borderWidth:1,borderColor:'#184454'},
  clipboard:{width:40,height:52,backgroundColor:'#E4DABA',borderWidth:3,borderColor:'#6B5D44',position:'relative'},clip:{alignSelf:'center',marginTop:-6,width:18,height:9,backgroundColor:'#81765F'},clipLine:{position:'absolute',left:6,height:2,backgroundColor:'#958C74'},
  clock:{width:49,height:49,borderRadius:25,backgroundColor:'#E8DFC0',borderWidth:5,borderColor:'#A67D3B',position:'relative'},clockInner:{position:'absolute',left:4,right:4,top:4,bottom:4,borderRadius:20,borderWidth:1,borderColor:'#C4B78F'},handA:{position:'absolute',left:20,top:8,width:3,height:16,backgroundColor:'#3D403B'},handB:{position:'absolute',left:21,top:21,width:13,height:3,backgroundColor:'#3D403B',transform:[{rotate:'20deg'}]},clockPin:{position:'absolute',left:19,top:19,width:7,height:7,backgroundColor:'#9A7434'},
  whiteboard:{width:72,height:51,backgroundColor:'#E8ECE3',borderWidth:4,borderColor:'#5F7074',position:'relative'},wbGridA:{position:'absolute',left:8,right:8,top:16,height:1,backgroundColor:'#C6CDC6'},wbGridB:{position:'absolute',left:8,right:8,top:31,height:1,backgroundColor:'#C6CDC6'},wbA:{position:'absolute',left:9,bottom:12,width:29,height:4,backgroundColor:'#43865A',transform:[{rotate:'-25deg'}]},wbB:{position:'absolute',left:35,bottom:20,width:21,height:4,backgroundColor:'#43865A',transform:[{rotate:'18deg'}]},wbDot:{position:'absolute',right:8,top:7,width:6,height:6,backgroundColor:'#C9A247'},wbTray:{position:'absolute',left:9,right:9,bottom:-6,height:6,backgroundColor:'#5A686A'},
  aum:{width:76,height:39,backgroundColor:'#071F27',borderWidth:3,borderColor:'#AE8A43',padding:6},aumLabel:{fontFamily:'PressStart2P',fontSize:5,color:'#94A8AA'},aumValue:{fontFamily:'PressStart2P',fontSize:7,color:'#79DB98',marginTop:5},aumBar:{position:'absolute',left:6,right:6,bottom:5,height:3,backgroundColor:'#376154'},
  nameplate:{width:58,height:24,backgroundColor:'#BD9135',borderWidth:3,borderColor:'#654719',padding:2},nameplateInner:{flex:1,borderWidth:1,borderColor:'#E8C869',alignItems:'center',justifyContent:'center'},nameplateText:{fontFamily:'PressStart2P',fontSize:6,color:'#342912'},
  mahogany:{width:73,height:54,backgroundColor:'#4C2B24',borderWidth:4,borderColor:'#231515',position:'relative'},woodFrame:{position:'absolute',left:5,right:5,top:5,bottom:5,borderWidth:2,borderColor:'#75473A'},woodLineA:{position:'absolute',left:10,top:14,width:49,height:3,backgroundColor:'#825044'},woodLineB:{position:'absolute',left:15,top:34,width:38,height:3,backgroundColor:'#825044'},
  railTop:{position:'absolute',left:5,right:5,top:17,height:5,backgroundColor:'#CBA64E'},railPostL:{position:'absolute',left:10,top:14,width:5,height:41,backgroundColor:'#CBA64E'},railPostC:{position:'absolute',left:43,top:14,width:5,height:37,backgroundColor:'#CBA64E'},railPostR:{position:'absolute',right:10,top:14,width:5,height:41,backgroundColor:'#CBA64E'},railFoot:{position:'absolute',left:7,right:7,bottom:13,height:4,backgroundColor:'#7A5C23'},
  ropePostL:{position:'absolute',left:11,top:18,width:6,height:40,backgroundColor:'#C39B3F'},ropePostR:{position:'absolute',right:11,top:18,width:6,height:40,backgroundColor:'#C39B3F'},ropeCapL:{position:'absolute',left:8,top:14,width:12,height:8,backgroundColor:'#E1BC5A'},ropeCapR:{position:'absolute',right:8,top:14,width:12,height:8,backgroundColor:'#E1BC5A'},ropeLine:{position:'absolute',left:17,top:25,width:58,height:7,backgroundColor:'#912B37',transform:[{rotate:'4deg'}]},
  skyline:{width:83,height:58,backgroundColor:'#071A23',borderWidth:3,borderColor:'#4F6870',flexDirection:'row',alignItems:'flex-end',gap:3,padding:5},building:{width:10,backgroundColor:'#294E61',position:'relative'},window:{position:'absolute',left:3,width:4,height:4,backgroundColor:'#E4C95E55'},
  portrait:{width:52,height:64,backgroundColor:'#62442F',borderWidth:4,borderColor:'#B38D4E',padding:4},portraitInner:{flex:1,backgroundColor:'#122B36',alignItems:'center',paddingTop:7},portraitHead:{width:15,height:15,backgroundColor:'#DA9986',borderWidth:1,borderColor:'#6A473E'},portraitBody:{width:28,height:27,backgroundColor:'#1F3541',marginTop:3},portraitShirt:{position:'absolute',left:19,top:26,width:8,height:16,backgroundColor:'#EDE7D7'},portraitTie:{position:'absolute',left:21,top:29,width:4,height:14,backgroundColor:'#AA2C32'},
  chandelierChain:{position:'absolute',left:44,top:0,width:4,height:18,backgroundColor:'#8E6D2D'},chandelierBar:{position:'absolute',left:7,right:7,top:17,height:6,backgroundColor:'#B8923E'},bulb:{position:'absolute',top:25,width:15,height:18,backgroundColor:'#F3DE88',borderWidth:2,borderColor:'#B89445'},
  rack:{width:79,height:43,backgroundColor:'#4B3225',borderWidth:4,borderColor:'#69492E',position:'relative'},rackRail:{position:'absolute',left:5,right:5,top:7,height:4,backgroundColor:'#8A6748'},visor:{position:'absolute',width:17,height:9,backgroundColor:'#459C63',borderWidth:2,borderColor:'#1E5A34'},visorBill:{position:'absolute',right:-6,top:3,width:8,height:4,backgroundColor:'#65BB7B'},
  calc:{width:40,height:49,backgroundColor:'#3D4B51',borderWidth:3,borderColor:'#172A30',padding:5},calcScreen:{height:11,backgroundColor:'#91CAA0',borderWidth:1,borderColor:'#335E41'},calcGrid:{marginTop:5,flexDirection:'row',flexWrap:'wrap',gap:2},calcKey:{width:5,height:5,backgroundColor:'#78868A'},
  bookShadow:{position:'absolute',left:19,right:19,bottom:11,height:4,backgroundColor:'#03111855'},bookA:{position:'absolute',left:16,bottom:14,width:58,height:12,backgroundColor:'#8A4037',borderWidth:2,borderColor:'#4C2420'},bookB:{position:'absolute',left:22,bottom:27,width:49,height:12,backgroundColor:'#3F6382',borderWidth:2,borderColor:'#243B4D'},page:{position:'absolute',left:29,bottom:40,width:34,height:7,backgroundColor:'#EADDB8'},bookRibbon:{position:'absolute',left:55,bottom:14,width:4,height:25,backgroundColor:'#D4AE4D'},
  espresso:{width:52,height:54,backgroundColor:'#4A595E',borderWidth:3,borderColor:'#1E3036',position:'relative'},espressoTop:{height:11,backgroundColor:'#29363A',borderBottomWidth:2,borderBottomColor:'#6D7A7D'},espressoGauge:{position:'absolute',right:6,top:15,width:10,height:10,borderRadius:5,backgroundColor:'#E6DFC4',borderWidth:2,borderColor:'#8E7750'},spout:{position:'absolute',left:11,top:20,width:18,height:5,backgroundColor:'#1A272B'},cup:{position:'absolute',left:16,bottom:4,width:17,height:13,borderWidth:3,borderTopWidth:0,borderColor:'#EEE3C4'},steam:{position:'absolute',left:22,top:-13,width:7,height:16,borderLeftWidth:2,borderColor:'#DAF4EF'},
  bellDome:{width:38,height:24,borderTopLeftRadius:19,borderTopRightRadius:19,backgroundColor:'#C89A36',borderWidth:2,borderColor:'#684A1A',position:'relative'},bellHighlight:{position:'absolute',left:7,top:5,width:15,height:4,backgroundColor:'#F0CE68'},bellBase:{width:44,height:8,backgroundColor:'#6F501E',borderWidth:1,borderColor:'#3E2A10'},
  tape:{width:88,height:16,backgroundColor:'#E9DFC3',borderWidth:2,borderColor:'#948568',justifyContent:'center',paddingHorizontal:5,transform:[{rotate:'-3deg'}]},tapeText:{fontSize:5,color:'#2E535D'},
  sign:{minWidth:88,maxWidth:120,minHeight:34,backgroundColor:'#0A1F27',borderWidth:4,borderColor:'#A9823E',padding:3},signInner:{flex:1,borderWidth:1,borderColor:'#E2BC5C',alignItems:'center',justifyContent:'center',paddingHorizontal:5,paddingVertical:4},signText:{fontFamily:'PressStart2P',fontSize:5,lineHeight:9,color:'#E8CE80',textAlign:'center'}
});
