import React, { useEffect, useRef } from 'react';
import { Animated, Easing, StyleSheet, View } from 'react-native';
import { decorItems, DecorSlot } from '../game/decor';
import { PixelText } from './PixelText';

const positions: Record<DecorSlot, object> = {
  'floor-left': { left: 34, bottom: 48 },
  'floor-center': { left: '43%', bottom: 47 },
  'floor-right': { right: 118, bottom: 48 },
  'wall-left': { left: 105, top: 54 },
  'wall-center': { left: '40%', top: 49 },
  'wall-right': { right: 112, top: 56 },
  ceiling: { left: '44%', top: 28 },
  corner: { right: 34, bottom: 48 },
};

function Pulse({ children, distance = 2 }: { children: React.ReactNode; distance?: number }) {
  const a = useRef(new Animated.Value(0)).current;
  useEffect(() => { const loop=Animated.loop(Animated.sequence([Animated.timing(a,{toValue:1,duration:900,easing:Easing.inOut(Easing.quad),useNativeDriver:true}),Animated.timing(a,{toValue:0,duration:900,easing:Easing.inOut(Easing.quad),useNativeDriver:true})]));loop.start();return()=>loop.stop();},[a]);
  return <Animated.View style={{opacity:a.interpolate({inputRange:[0,1],outputRange:[.72,1]}),transform:[{translateY:a.interpolate({inputRange:[0,1],outputRange:[0,-distance]})}]}}>{children}</Animated.View>;
}

function Blink({ style }: { style?: object }) {
  const a=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const loop=Animated.loop(Animated.sequence([Animated.timing(a,{toValue:1,duration:420,useNativeDriver:true}),Animated.delay(780),Animated.timing(a,{toValue:0,duration:260,useNativeDriver:true}),Animated.delay(520)]));loop.start();return()=>loop.stop();},[a]);
  return <Animated.View style={[styles.blink,{opacity:a},style]}/>;
}

function DecorVisual({ id }: { id: string }) {
  if(id==='desk') return <View style={styles.desk}><View style={styles.deskTop}/><View style={styles.deskDrawer}/><View style={styles.deskLegL}/><View style={styles.deskLegR}/><View style={styles.paper}/><View style={styles.pen}/></View>;
  if(id==='chair') return <View style={styles.chair}><View style={styles.chairBack}/><View style={styles.chairSeat}/><View style={styles.chairStem}/><View style={styles.chairBase}/><View style={styles.wheelL}/><View style={styles.wheelR}/></View>;
  if(id==='filing') return <View style={styles.filing}>{[0,1,2].map(i=><View key={i} style={styles.drawer}><View style={styles.drawerHandle}/></View>)}</View>;
  if(id==='meeting') return <View style={styles.meeting}><View style={styles.meetingTop}/><View style={styles.meetingLeg}/><View style={[styles.miniChair,{left:-9}]}/><View style={[styles.miniChair,{right:-9}]}/></View>;
  if(id==='copier') return <View style={styles.copier}><View style={styles.copierTop}/><View style={styles.copierTray}/><Blink style={{right:5,top:13}}/><Pulse distance={4}><View style={styles.paperOut}/></Pulse></View>;
  if(id==='banker-lamp') return <View style={styles.lamp}><Pulse distance={1}><View style={styles.lampGlow}/></Pulse><View style={styles.lampShade}/><View style={styles.lampStem}/><View style={styles.lampBase}/></View>;
  if(id==='coffee-cart') return <View style={styles.cart}><View style={styles.cartTop}/><View style={styles.cartShelf}/><View style={styles.cartLegL}/><View style={styles.cartLegR}/><View style={styles.mug}/></View>;
  if(id==='water-cooler') return <View style={styles.cooler}><View style={styles.coolerBottle}/><View style={styles.coolerBase}/><View style={styles.coolerTap}/></View>;
  if(id==='trash') return <View style={styles.trash}><View style={styles.trashRim}/><View style={styles.trashStripe}/></View>;
  if(id==='conference-phone') return <View style={styles.phone}><View style={styles.phoneBody}/><View style={styles.phoneScreen}/><View style={styles.phoneButton}/></View>;
  if(id==='ticker') return <View style={styles.ticker}><Blink style={{left:5,top:6}}/><PixelText style={styles.tickerText}>SHRP ▲4.2  AUM ▲  KRLL ▼</PixelText></View>;
  if(id==='terminal') return <View style={styles.terminal}><View style={styles.screen}><PixelText style={styles.screenText}>SHRP</PixelText><View style={styles.graphA}/><View style={styles.graphB}/><Blink style={{right:4,top:4}}/></View><View style={styles.screenStand}/><View style={styles.keyboard}/></View>;
  if(id==='chart') return <View style={styles.poster}><View style={styles.gridLineA}/><View style={styles.gridLineB}/><View style={styles.chartLine1}/><View style={styles.chartLine2}/><View style={styles.chartDot}/></View>;
  if(id==='pnl') return <View style={styles.pnl}><PixelText style={styles.pnlText}>P&L</PixelText><View style={styles.pnlGreen}/><View style={styles.pnlGreen2}/><View style={styles.pnlRed}/><Blink style={{right:4,top:4}}/></View>;
  if(id==='bull') return <View style={styles.bull}><View style={styles.bullBody}/><View style={styles.bullHead}/><View style={styles.bullLegA}/><View style={styles.bullLegB}/><View style={styles.hornL}/><View style={styles.hornR}/><Pulse distance={1}><View style={styles.bullSpark}/></Pulse></View>;
  if(id==='briefcase') return <View style={styles.briefcase}><View style={styles.handle}/><View style={styles.caseLatch}/><View style={styles.caseStripe}/></View>;
  if(id==='vault'||id==='safe') return <View style={styles.vault}><View style={styles.vaultInset}><View style={styles.vaultWheel}><View style={styles.vaultSpokeH}/><View style={styles.vaultSpokeV}/></View></View></View>;
  if(id==='earnings'||id==='buy-dip'||id==='compliance-sign'||id==='private-equity'||id==='shell-street-logo'||id==='private-bank') { const label=id==='earnings'?'EARNINGS CALL':id==='buy-dip'?'BUY THE DIP':id==='compliance-sign'?'COMPLIANCE IS WATCHING':id==='private-equity'?'PRIVATE EQUITY PRAWNS':id==='shell-street-logo'?'SHELL STREET CAPITAL':'PRIVATE AQUATIC BANK'; return <View style={styles.sign}><PixelText style={styles.signText}>{label}</PixelText></View>; }
  if(id==='abacus') return <View style={styles.abacus}>{[0,1,2].map(r=><View key={r} style={[styles.abacusRod,{top:5+r*7}]}>{[0,1,2,3].map(c=><View key={c} style={[styles.abacusBead,{left:4+c*7+(r%2)*2}]}/>)}</View>)}</View>;
  if(id==='clipboard') return <View style={styles.clipboard}><View style={styles.clipTop}/><View style={styles.clipLine}/><View style={[styles.clipLine,{top:15,width:18}]}/></View>;
  if(id==='clock') return <View style={styles.clock}><View style={styles.clockHandA}/><View style={styles.clockHandB}/></View>;
  if(id==='whiteboard') return <View style={styles.whiteboard}><View style={styles.wbArrowA}/><View style={styles.wbArrowB}/><View style={styles.wbMarker}/></View>;
  if(id==='aum-display') return <View style={styles.aum}><PixelText style={styles.aumTitle}>AUM</PixelText><PixelText style={styles.aumValue}>$12.8M</PixelText><Blink style={{right:4,top:4}}/></View>;
  if(id==='nameplate') return <View style={styles.nameplate}><PixelText style={styles.nameplateText}>CEO</PixelText></View>;
  if(id==='mahogany') return <View style={styles.mahogany}><View style={styles.woodLine}/><View style={[styles.woodLine,{top:22,left:9,width:30}]}/></View>;
  if(id==='brass-rail') return <View style={styles.rail}><View style={styles.railPostL}/><View style={styles.railPostC}/><View style={styles.railPostR}/></View>;
  if(id==='velvet-rope') return <View style={styles.rope}><View style={styles.ropePostL}/><View style={styles.ropePostR}/><View style={styles.ropeLine}/></View>;
  if(id==='skyline') return <View style={styles.skyline}>{[18,31,23,38,27,33].map((h,i)=><View key={i} style={[styles.building,{height:h}]}/>)}</View>;
  if(id==='ceo-portrait') return <View style={styles.portrait}><View style={styles.portraitHead}/><View style={styles.portraitBody}/><View style={styles.portraitTie}/></View>;
  if(id==='chandelier') return <View style={styles.chandelier}><View style={styles.chandelierBar}/>{[1,15,29].map(left=><Pulse key={left} distance={1}><View style={[styles.lightBulb,{left}]}/></Pulse>)}</View>;
  if(id==='visor-rack') return <View style={styles.visorRack}>{[5,22,39].map((left,i)=><View key={left} style={[styles.visor,{left,top:i===1?13:7}]}/>)}</View>;
  if(id==='calculator') return <View style={styles.calculator}><View style={styles.calcScreen}/><View style={styles.calcGrid}/></View>;
  if(id==='ledger') return <View style={styles.ledger}><View style={styles.ledgerBook1}/><View style={styles.ledgerBook2}/><View style={styles.ledgerPage}/></View>;
  if(id==='liquidity-plaque') return <View style={styles.plaque}><PixelText style={styles.plaqueText}>LIQUIDITY POOL</PixelText></View>;
  if(id==='espresso') return <View style={styles.espresso}><View style={styles.espressoTop}/><View style={styles.espressoSpout}/><View style={styles.espressoCup}/><Pulse distance={5}><View style={styles.steam}/></Pulse></View>;
  if(id==='opening-bell') return <View style={styles.bell}><Pulse distance={1}><View style={styles.bellDome}/></Pulse><View style={styles.bellBase}/></View>;
  if(id==='ticker-tape') return <View style={styles.tape}><PixelText style={styles.tapeText}>BUY  SELL  HOLD  BUY</PixelText></View>;
  return <View style={styles.generic}><PixelText style={styles.genericText}>$</PixelText></View>;
}

export function TankOfficeDecor({ placed }: { placed: Partial<Record<DecorSlot, string>> }) {
  return <>{Object.entries(placed).map(([slot,id])=>{
    if(!id||!decorItems.some(item=>item.id===id)) return null;
    return <View pointerEvents="none" key={`${slot}-${id}`} style={[styles.item,positions[slot as DecorSlot]]}><DecorVisual id={id}/></View>;
  })}</>;
}

const styles=StyleSheet.create({
  item:{position:'absolute',zIndex:8},generic:{width:34,height:28,backgroundColor:'#C79C4A',borderWidth:2,borderColor:'#5E4727',alignItems:'center',justifyContent:'center'},genericText:{fontSize:8,color:'#2C281F'},blink:{position:'absolute',width:5,height:5,borderRadius:3,backgroundColor:'#72F194'},
  desk:{width:60,height:39},deskTop:{position:'absolute',top:8,width:60,height:8,backgroundColor:'#80543B',borderWidth:2,borderColor:'#32231B'},deskDrawer:{position:'absolute',left:31,top:15,width:21,height:12,backgroundColor:'#65422F',borderWidth:1,borderColor:'#302018'},deskLegL:{position:'absolute',left:7,top:16,width:6,height:23,backgroundColor:'#52372A'},deskLegR:{position:'absolute',right:7,top:16,width:6,height:23,backgroundColor:'#52372A'},paper:{position:'absolute',left:8,top:3,width:20,height:6,backgroundColor:'#EFE7CC'},pen:{position:'absolute',left:33,top:4,width:14,height:2,backgroundColor:'#73A7C9',transform:[{rotate:'-8deg'}]},
  chair:{width:36,height:43},chairBack:{width:28,height:19,borderRadius:7,backgroundColor:'#30454E',borderWidth:2,borderColor:'#142B33'},chairSeat:{width:32,height:9,backgroundColor:'#3F5862',marginTop:2},chairStem:{width:4,height:10,backgroundColor:'#8B999D',alignSelf:'center'},chairBase:{width:24,height:3,backgroundColor:'#68797F',alignSelf:'center'},wheelL:{position:'absolute',left:5,bottom:0,width:5,height:5,borderRadius:3,backgroundColor:'#1A252A'},wheelR:{position:'absolute',right:5,bottom:0,width:5,height:5,borderRadius:3,backgroundColor:'#1A252A'},
  filing:{width:31,height:48,backgroundColor:'#53656D',padding:4,gap:3,borderWidth:2,borderColor:'#24373D'},drawer:{height:11,backgroundColor:'#829097',borderWidth:1,borderColor:'#36474D'},drawerHandle:{width:8,height:2,backgroundColor:'#27363B',alignSelf:'center',marginTop:4},meeting:{width:65,height:29},meetingTop:{width:65,height:10,borderRadius:5,backgroundColor:'#82563A',borderWidth:2,borderColor:'#39271D'},meetingLeg:{width:6,height:18,backgroundColor:'#5B3B29',alignSelf:'center'},miniChair:{position:'absolute',bottom:1,width:10,height:17,borderWidth:2,borderColor:'#485D65'},
  copier:{width:42,height:45,backgroundColor:'#CBD1CE',borderWidth:2,borderColor:'#59666A'},copierTop:{height:10,backgroundColor:'#424F55'},copierTray:{position:'absolute',left:8,bottom:6,width:24,height:14,backgroundColor:'#EEF0EB',borderWidth:1,borderColor:'#7A8585'},paperOut:{position:'absolute',left:7,top:-6,width:27,height:9,backgroundColor:'#FFF7DC',borderWidth:1,borderColor:'#B6AB8B'},lamp:{width:40,height:43},lampGlow:{position:'absolute',left:6,top:6,width:31,height:16,borderRadius:12,backgroundColor:'#A7FFB52A'},lampShade:{position:'absolute',top:6,left:8,width:26,height:11,backgroundColor:'#2E915C',borderWidth:2,borderColor:'#174C31',transform:[{skewX:'-12deg'}]},lampStem:{position:'absolute',left:20,top:17,width:4,height:18,backgroundColor:'#CBAE5B'},lampBase:{position:'absolute',left:10,bottom:3,width:24,height:5,backgroundColor:'#987837'},
  cart:{width:48,height:36},cartTop:{width:48,height:9,backgroundColor:'#8B5B38',borderWidth:2,borderColor:'#4A321F'},cartShelf:{position:'absolute',left:5,top:19,width:38,height:5,backgroundColor:'#68432D'},cartLegL:{position:'absolute',left:7,top:9,width:4,height:26,backgroundColor:'#513523'},cartLegR:{position:'absolute',right:7,top:9,width:4,height:26,backgroundColor:'#513523'},mug:{position:'absolute',right:7,top:1,width:9,height:8,borderWidth:2,borderColor:'#F0E6C7'},cooler:{width:31,height:50},coolerBottle:{width:20,height:23,borderRadius:7,backgroundColor:'#77D1E0',alignSelf:'center',borderWidth:2,borderColor:'#B8F4F6'},coolerBase:{width:31,height:27,backgroundColor:'#E0E6E3',borderWidth:2,borderColor:'#7B8A8A'},coolerTap:{position:'absolute',right:2,top:28,width:8,height:3,backgroundColor:'#3C5960'},trash:{width:26,height:31,backgroundColor:'#596A70',borderBottomLeftRadius:5,borderBottomRightRadius:5,borderWidth:2,borderColor:'#2B3D42'},trashRim:{height:5,backgroundColor:'#839398'},trashStripe:{marginTop:6,width:18,height:2,alignSelf:'center',backgroundColor:'#34484E'},phone:{width:39,height:25},phoneBody:{position:'absolute',bottom:0,width:39,height:16,borderRadius:6,backgroundColor:'#283D46',borderWidth:2,borderColor:'#15252B'},phoneScreen:{position:'absolute',left:13,bottom:4,width:13,height:6,backgroundColor:'#7FC39B'},phoneButton:{position:'absolute',left:4,bottom:5,width:4,height:4,backgroundColor:'#9DAAAD'},
  ticker:{width:145,height:21,backgroundColor:'#071A22',borderWidth:2,borderColor:'#A8843D',justifyContent:'center',paddingHorizontal:7},tickerText:{fontSize:6,color:'#72F0A1',letterSpacing:.4},terminal:{width:52,height:45},screen:{width:46,height:29,backgroundColor:'#06171E',borderWidth:3,borderColor:'#516F76',position:'relative',padding:4},screenText:{fontSize:5,color:'#7FEFA2'},graphA:{position:'absolute',left:7,bottom:7,width:18,height:2,backgroundColor:'#6BE39B',transform:[{rotate:'-18deg'}]},graphB:{position:'absolute',left:22,bottom:12,width:13,height:2,backgroundColor:'#6BE39B',transform:[{rotate:'24deg'}]},screenStand:{width:5,height:5,backgroundColor:'#66777B',alignSelf:'center'},keyboard:{width:52,height:7,backgroundColor:'#4D5E63',borderWidth:1,borderColor:'#28383D'},
  poster:{width:52,height:39,backgroundColor:'#F3E9CA',borderWidth:3,borderColor:'#6A5035'},gridLineA:{position:'absolute',left:5,right:5,top:12,height:1,backgroundColor:'#C9BFA4'},gridLineB:{position:'absolute',left:5,right:5,top:23,height:1,backgroundColor:'#C9BFA4'},chartLine1:{position:'absolute',left:7,bottom:9,width:22,height:3,backgroundColor:'#39965C',transform:[{rotate:'-24deg'}]},chartLine2:{position:'absolute',left:25,bottom:15,width:16,height:3,backgroundColor:'#39965C',transform:[{rotate:'22deg'}]},chartDot:{position:'absolute',right:6,top:6,width:5,height:5,borderRadius:3,backgroundColor:'#E1B94E'},pnl:{width:54,height:38,backgroundColor:'#0D252C',borderWidth:2,borderColor:'#AA8F50',padding:5},pnlText:{fontSize:6,color:'#F2D998'},pnlGreen:{width:33,height:4,backgroundColor:'#65D48C',marginTop:3},pnlGreen2:{width:24,height:4,backgroundColor:'#65D48C',marginTop:2},pnlRed:{width:17,height:4,backgroundColor:'#E06A61',marginTop:2},
  bull:{width:50,height:34},bullBody:{position:'absolute',left:10,top:13,width:27,height:13,backgroundColor:'#C89843',borderWidth:1,borderColor:'#6F4C20'},bullHead:{position:'absolute',right:2,top:10,width:14,height:12,backgroundColor:'#D2A950'},bullLegA:{position:'absolute',left:13,bottom:1,width:4,height:10,backgroundColor:'#8B672B'},bullLegB:{position:'absolute',left:31,bottom:1,width:4,height:10,backgroundColor:'#8B672B'},hornL:{position:'absolute',right:7,top:4,width:10,height:3,backgroundColor:'#F0DFAC',transform:[{rotate:'-28deg'}]},hornR:{position:'absolute',right:-1,top:6,width:9,height:3,backgroundColor:'#F0DFAC',transform:[{rotate:'28deg'}]},bullSpark:{position:'absolute',right:0,top:0,width:5,height:5,backgroundColor:'#FFE88A',transform:[{rotate:'45deg'}]},briefcase:{width:43,height:27,backgroundColor:'#D2A747',borderWidth:2,borderColor:'#6D4E20'},handle:{position:'absolute',left:13,top:-8,width:15,height:8,borderWidth:2,borderBottomWidth:0,borderColor:'#A47C31'},caseLatch:{position:'absolute',left:19,top:10,width:6,height:6,backgroundColor:'#FFF0A6',borderWidth:1,borderColor:'#8C6729'},caseStripe:{position:'absolute',left:2,right:2,top:13,height:2,backgroundColor:'#936B28'},
  vault:{width:52,height:52,borderRadius:26,backgroundColor:'#53676D',borderWidth:5,borderColor:'#263A40',padding:5},vaultInset:{flex:1,borderRadius:20,borderWidth:2,borderColor:'#91A0A2',alignItems:'center',justifyContent:'center'},vaultWheel:{width:23,height:23,borderRadius:12,borderWidth:3,borderColor:'#D3B46E'},vaultSpokeH:{position:'absolute',top:8,left:1,width:15,height:2,backgroundColor:'#D3B46E'},vaultSpokeV:{position:'absolute',left:8,top:1,width:2,height:15,backgroundColor:'#D3B46E'},sign:{minWidth:84,maxWidth:125,minHeight:25,backgroundColor:'#132F38',borderWidth:2,borderColor:'#D1AE56',alignItems:'center',justifyContent:'center',paddingHorizontal:7,paddingVertical:5},signText:{fontSize:5,color:'#F4D781',textAlign:'center'},abacus:{width:47,height:29,borderWidth:3,borderColor:'#744B2E',backgroundColor:'#C19457',position:'relative'},abacusRod:{position:'absolute',left:3,right:3,height:1,backgroundColor:'#54351F'},abacusBead:{position:'absolute',top:-3,width:5,height:6,borderRadius:3,backgroundColor:'#3D7A8D'},clipboard:{width:31,height:40,backgroundColor:'#EDE5C9',borderWidth:2,borderColor:'#76694E',position:'relative'},clipTop:{alignSelf:'center',marginTop:-4,width:14,height:7,backgroundColor:'#8E8368'},clipLine:{position:'absolute',left:5,top:10,width:20,height:2,backgroundColor:'#9A927B'},clock:{width:38,height:38,borderRadius:19,backgroundColor:'#EFE6C8',borderWidth:4,borderColor:'#B38B49'},clockHandA:{position:'absolute',left:16,top:6,width:3,height:13,backgroundColor:'#4B4B43'},clockHandB:{position:'absolute',left:17,top:17,width:10,height:3,backgroundColor:'#4B4B43',transform:[{rotate:'20deg'}]},whiteboard:{width:62,height:40,backgroundColor:'#F0F1E9',borderWidth:3,borderColor:'#69797B'},wbArrowA:{position:'absolute',left:8,bottom:9,width:24,height:3,backgroundColor:'#488B61',transform:[{rotate:'-25deg'}]},wbArrowB:{position:'absolute',left:27,bottom:15,width:18,height:3,backgroundColor:'#488B61',transform:[{rotate:'18deg'}]},wbMarker:{position:'absolute',left:8,bottom:3,width:31,height:2,backgroundColor:'#34464A'},aum:{width:66,height:31,backgroundColor:'#0B2229',borderWidth:2,borderColor:'#BA984F',padding:5},aumTitle:{fontSize:5,color:'#8FA7AA'},aumValue:{fontSize:8,color:'#7DE6A0',marginTop:2},
  nameplate:{width:48,height:18,backgroundColor:'#D4AA44',borderWidth:2,borderColor:'#76561F',alignItems:'center',justifyContent:'center'},nameplateText:{fontSize:6,color:'#332916'},mahogany:{width:60,height:45,backgroundColor:'#5A3329',borderWidth:3,borderColor:'#281817',position:'relative'},woodLine:{position:'absolute',left:7,top:9,width:43,height:3,backgroundColor:'#825244'},rail:{width:72,height:30,borderTopWidth:4,borderColor:'#D3B15D'},railPostL:{position:'absolute',left:4,top:0,width:4,height:28,backgroundColor:'#D3B15D'},railPostC:{position:'absolute',left:34,top:0,width:4,height:24,backgroundColor:'#D3B15D'},railPostR:{position:'absolute',right:4,top:0,width:4,height:28,backgroundColor:'#D3B15D'},rope:{width:68,height:31},ropePostL:{position:'absolute',left:3,top:3,width:5,height:28,backgroundColor:'#D0A24D'},ropePostR:{position:'absolute',right:3,top:3,width:5,height:28,backgroundColor:'#D0A24D'},ropeLine:{position:'absolute',left:8,top:9,width:53,height:6,borderRadius:4,backgroundColor:'#9C2F3B',transform:[{rotate:'5deg'}]},skyline:{width:90,height:48,backgroundColor:'#0C2029',flexDirection:'row',alignItems:'flex-end',gap:4,padding:6,borderWidth:2,borderColor:'#536D77'},building:{width:10,backgroundColor:'#35566A'},portrait:{width:42,height:52,backgroundColor:'#704C35',borderWidth:3,borderColor:'#C4A05A',alignItems:'center',paddingTop:7},portraitHead:{width:12,height:12,borderRadius:6,backgroundColor:'#E1A08E'},portraitBody:{width:22,height:22,backgroundColor:'#263E4A',marginTop:3},portraitTie:{position:'absolute',left:19,top:23,width:4,height:12,backgroundColor:'#B83435'},chandelier:{width:48,height:29},chandelierBar:{position:'absolute',top:0,left:0,width:46,height:5,backgroundColor:'#C3A24D'},lightBulb:{position:'absolute',top:8,width:11,height:13,backgroundColor:'#FFEBA1',borderRadius:6,borderWidth:1,borderColor:'#CFAE5D'},
  visorRack:{width:57,height:35,borderWidth:3,borderColor:'#6D4E34',backgroundColor:'#553B2A'},visor:{position:'absolute',width:13,height:7,backgroundColor:'#4DA46A',borderWidth:1,borderColor:'#245C36'},calculator:{width:32,height:38,backgroundColor:'#47545B',borderWidth:2,borderColor:'#1E2F35'},calcScreen:{margin:4,width:20,height:8,backgroundColor:'#9BD7A8'},calcGrid:{marginLeft:4,width:20,height:16,borderTopWidth:4,borderBottomWidth:4,borderColor:'#8C999C'},ledger:{width:43,height:27},ledgerBook1:{position:'absolute',bottom:0,width:42,height:9,backgroundColor:'#99483A',borderWidth:1,borderColor:'#5E2A23'},ledgerBook2:{position:'absolute',bottom:10,left:5,width:35,height:9,backgroundColor:'#466B8C',borderWidth:1,borderColor:'#283E51'},ledgerPage:{position:'absolute',left:11,top:1,width:21,height:4,backgroundColor:'#F0E6C8'},plaque:{width:70,height:19,backgroundColor:'#73543A',borderWidth:2,borderColor:'#C8A66A',alignItems:'center',justifyContent:'center'},plaqueText:{fontSize:4,color:'#F1D9A8'},espresso:{width:42,height:42,backgroundColor:'#56656A',borderWidth:2,borderColor:'#27383D',position:'relative'},espressoTop:{height:9,backgroundColor:'#313D41'},espressoSpout:{position:'absolute',left:10,top:16,width:15,height:4,backgroundColor:'#202C30'},espressoCup:{position:'absolute',left:13,bottom:3,width:14,height:10,borderWidth:2,borderTopWidth:0,borderColor:'#F0E6C7'},steam:{position:'absolute',left:17,top:-11,width:5,height:12,borderLeftWidth:2,borderColor:'#DFF8F3',borderRadius:5},bell:{width:34,height:28},bellDome:{width:29,height:18,borderTopLeftRadius:15,borderTopRightRadius:15,backgroundColor:'#D0A33B',borderWidth:1,borderColor:'#76561F'},bellBase:{width:34,height:6,backgroundColor:'#7D5B21'},tape:{width:78,height:12,backgroundColor:'#EFE6C9',borderWidth:1,borderColor:'#9B8E6C',justifyContent:'center',paddingHorizontal:4,transform:[{rotate:'-4deg'}]},tapeText:{fontSize:4,color:'#355461'},
});
